/**
 * 重新组织Genshin Impact角色数据的JavaScript脚本
 * 按照指定字段顺序输出角色数据
 * 该脚本用于将原始角色数据转换为适合导入数据库的格式
 */
const characters = {
  'Albedo': { 
    name: '阿贝多', 
    element: '岩元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '蒙德', 
    description: '西风骑士团的首席炼金术士，“黄金”莱茵多特的造物。', 
    image: 'images/characters/abeiduo.png', 
    skills: ['创生法·拟造阳华', '诞生式·大地之潮', '辉光·启明星'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '玄岩之塔', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '血玉之枝', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1000,
    base_atk: 52,
    base_def: 31,
    character_story: '阿贝多是西风骑士团的首席炼金术士，他的真实身份是“黄金”莱茵多特创造的人造人。他在雪山深处进行着神秘的研究，探索着世界的真相。',
    constellations: ['白垩之子', '创生法·拟造阳华', '诞生式·大地之潮', '辉光·启明星', '无瑕的纯白', '黄金的血脉'],
    passive_talents: ['天才的创造', '白垩的子嗣', '大地的馈赠'],
    voice_actor_cn: 'Mace',
    voice_actor_jp: '野岛健儿'
  },
  'Barbara': { 
    name: '芭芭拉', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 4, 
    region: '蒙德', 
    description: '西风教会的治愈者，擅长使用水元素治疗。', 
    image: 'images/characters/barbara.png', 
    skills: ['圣歌·抚慰', '圣歌·净化', '圣歌·祝福'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '血玉之枝', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 950,
    base_atk: 48,
    base_def: 29,
    character_story: '芭芭拉是西风教会的祈礼牧师，同时也是蒙德城的偶像歌手。她以清纯可爱的形象和治愈的歌声受到市民的喜爱，用她的水元素力量为人们带来希望和治愈。',
    constellations: ['光辉的季节', '圣歌·抚慰', '圣歌·净化', '圣歌·祝福', '偶像的魅力', '奇迹的歌声'],
    passive_talents: ['治愈的歌声', '偶像的光环', '水之祈愿'],
    voice_actor_cn: '宋媛媛',
    voice_actor_jp: '鬼头明里'
  },
  'Diluc': { 
    name: '迪卢克', 
    element: '火元素', 
    weapon: '双手剑', 
    rarity: 5, 
    region: '蒙德', 
    description: '蒙德城的酒馆老板，火焰与黑暗的掌控者。', 
    image: 'images/characters/diluc.png', 
    skills: ['逆焰之刃', '冰潮的涡旋', '凝浪之光剑'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['抗争的教导', '抗争的指引', '抗争的哲学', '血玉之枝', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1050,
    base_atk: 56,
    base_def: 33,
    character_story: '迪卢克是蒙德城最富有的家族——莱艮芬德家族的继承人。他曾是西风骑士团的骑兵队长，但因父亲的死而离开骑士团，成为了暗中守护蒙德的“暗夜英雄”。',
    constellations: ['炎之魔女', '逆焰之刃', '冰潮的涡旋', '凝浪之光剑', '火焰的意志', '暗夜的守护'],
    passive_talents: ['火焰的掌控', '暗夜的步伐', '正义的裁决'],
    voice_actor_cn: '马洋',
    voice_actor_jp: '小野贤章'
  },
  'Keqing': { 
    name: '刻晴', 
    element: '雷元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '璃月', 
    description: '璃月港的“玉衡”星，雷厉风行的领导者。', 
    image: 'images/characters/keqing.png', 
    skills: ['云来剑法', '星斗归位', '天街巡游'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷光棱镜', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 54,
    base_def: 32,
    character_story: '刻晴是璃月港的“玉衡”星，雷厉风行的领导者。她以凡人之躯比肩神明，坚信人类的命运应由自己掌握，积极推动璃月港的现代化发展。',
    constellations: ['雷厉', '星斗归位', '天街巡游', '雷楔', '雷罚', '雷劫'],
    passive_talents: ['玉衡之贵', '星斗的指引', '雷元素的亲和'],
    voice_actor_cn: '杨梦露',
    voice_actor_jp: '高桥李依'
  },
  'Venti': { 
    name: '温迪', 
    element: '风元素', 
    weapon: '弓', 
    rarity: 5, 
    region: '蒙德', 
    description: '蒙德的吟游诗人，风神的化身。', 
    image: 'images/characters/venti.png', 
    skills: ['风之诗篇', '风之舞步', '风之咏叹'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 980,
    base_atk: 50,
    base_def: 30,
    character_story: '温迪是蒙德的吟游诗人，也是风神巴巴托斯的化身。他以轻松幽默的性格和美妙的歌声闻名，虽然看起来像个顽皮的孩子，但实际上拥有着深厚的智慧和强大的力量。',
    constellations: ['风之诗篇', '风之舞步', '风之咏叹', '风神的祝福', '自由之风', '诗人的传说'],
    passive_talents: ['风神的眷顾', '风之诗篇', '风之舞步'],
    voice_actor_cn: '李兰陵',
    voice_actor_jp: '石川英郎'
  },
  'Zhongli': { 
    name: '钟离', 
    element: '岩元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '璃月', 
    description: '往生堂的神秘客卿，真实身份是岩王帝君。', 
    image: 'images/characters/zhongli.png', 
    skills: ['岩雨', '地心', '天星'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1200,
    base_atk: 48,
    base_def: 42,
    character_story: '钟离是璃月港的神秘客卿，真实身份是岩王帝君。他以温和睿智的形象深受民众喜爱，同时拥有着悠久的历史和强大的力量。他致力于保护璃月的和平与发展。',
    constellations: ['岩王帝君', '岩雨', '地心', '天星', '岩之守护', '岩王的智慧'],
    passive_talents: ['岩王的守护', '岩之庇护', '岩王的威严'],
    voice_actor_cn: '吴磊',
    voice_actor_jp: '中井和哉'
  },
  'Raiden Shogun': { 
    name: '雷电将军', 
    element: '雷元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '稻妻', 
    description: '稻妻的统治者，追求永恒的雷神。', 
    image: 'images/characters/leidian.png', 
    skills: ['神变·恶曜开眼', '神变·雷罚恶曜', '梦想真说'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷王的雷电', '旧武器零件', '破损的面具', '污秽的面具'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '雷电将军的战利品', '旧武器零件', '破损的面具', '污秽的面具'],
    base_hp: 1100,
    base_atk: 58,
    base_def: 36,
    character_story: '雷电将军是稻妻的统治者，追求永恒的雷神。她以强大的雷电之力统治着稻妻，为了达成自己的目标不惜一切代价，是一位既强大又神秘的领袖人物。',
    constellations: ['雷神的威严', '神变·恶曜开眼', '神变·雷罚恶曜', '梦想真说', '雷神的意志', '永恒的雷电'],
    passive_talents: ['雷神的威严', '雷电的统治', '永恒的雷电'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石川由依'
  },
  'Nahida': { 
    name: '纳西妲', 
    element: '草元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '须弥', 
    description: '须弥的神明，小吉祥草王。', 
    image: 'images/characters/naxida.png', 
    skills: ['普攻', '所闻遍计', '诸法空相'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '纳西妲的战利品', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 960,
    base_atk: 46,
    base_def: 30,
    character_story: '纳西妲是须弥的神明，小吉祥草王。她以智慧和知识著称，是须弥教令院的象征性人物。她拥有丰富的知识和强大的草元素力量，是须弥智慧的化身。',
    constellations: ['小吉祥草王', '所闻遍计', '诸法空相', '智慧之源', '草神的眷顾', '知识的传承'],
    passive_talents: ['智慧的传承', '草元素的亲和', '知识的启示'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '茅野爱衣'
  },
  'Furina': { 
    name: '芙宁娜', 
    element: '水元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '枫丹', 
    description: '枫丹的水之神，掌管正义与审判。', 
    image: 'images/characters/funingna.png', 
    skills: ['普攻', '水之誓约', '裁决之潮'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '水之滴', '净水之心', '纯水之愿', '浓缩树脂'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '芙宁娜的战利品', '净水之心', '纯水之愿', '浓缩树脂'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '芙宁娜是枫丹的水之神，掌管正义与审判。她以水元素的力量维护着枫丹的秩序和正义，是一位强大而公正的神明。',
    constellations: ['水之神', '水之誓约', '裁决之潮', '正义的化身', '审判之水', '水神的威严'],
    passive_talents: ['正义的审判', '水元素的亲和', '审判之水'],
    voice_actor_cn: '赵爽',
    voice_actor_jp: '石见舞菜香'
  },
  'Xiao': { 
    name: '魈', 
    element: '风元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '璃月', 
    description: '璃月港的“护法夜叉”，守护璃月已有千年。', 
    image: 'images/characters/xiao.png', 
    skills: ['风轮两立', '靖妖傩舞', '降魔大圣'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '幼岩龙蜥的玉髓', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '风魔龙的 plume', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1080,
    base_atk: 54,
    base_def: 35,
    character_story: '魈是璃月港的“护法夜叉”，守护璃月已有千年。他以风元素的力量保护着璃月的人民，是一个沉默寡言但内心善良的守护者。',
    constellations: ['护法夜叉', '风轮两立', '靖妖傩舞', '降魔大圣', '风神的眷顾', '夜叉的守护'],
    passive_talents: ['夜叉的守护', '风元素的亲和', '风神的祝福'],
    voice_actor_cn: '李兰陵',
    voice_actor_jp: '杉田智和'
  },
  'Hu Tao': { 
    name: '胡桃', 
    element: '火元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '璃月', 
    description: '璃月港"往生堂"的堂主，性格活泼开朗。', 
    image: 'images/characters/hutao.png', 
    skills: ['魂引之仪', '蝶引来生', '安神秘法'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '燃愿玛瑙', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '古岩龙蜥的 aerosiderite', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1150,
    base_atk: 58,
    base_def: 34,
    character_story: '胡桃是璃月港"往生堂"的堂主，性格活泼开朗。她以独特的魅力和精湛的医术在璃月港广受尊敬，虽然看似调皮，但其实非常关心他人。',
    constellations: ['往生堂的堂主', '魂引之仪', '蝶引来生', '安神秘法', '生命的延续', '冥界的使者'],
    passive_talents: ['生命的守护', '冥界的祝福', '往生堂的传承'],
    voice_actor_cn: '赵爽',
    voice_actor_jp: '小松未可子'
  },
  'Ganyu': { 
    name: '甘雨', 
    element: '冰元素', 
    weapon: '弓', 
    rarity: 5, 
    region: '璃月', 
    description: '“七星”的秘书，半人半仙的存在，工作认真负责。', 
    image: 'images/characters/ganyu.png', 
    skills: ['流天射术', '山泽麟迹', '降众天华'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1080,
    base_atk: 52,
    base_def: 35,
    character_story: '甘雨是璃月港“七星”的秘书，半人半仙的存在。她以优雅的气质和卓越的能力在璃月港工作，是璃月的守护者之一。',
    constellations: ['七星的秘书', '流天射术', '山泽麟迹', '降众天华', '天华的守护', '星辰的祝福'],
    passive_talents: ['天华的守护', '星辰的庇护', '天华的智慧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Kaedehara Kazuha': { 
    name: '枫原万叶', 
    element: '风元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '稻妻', 
    description: '稻妻的浪人武士，曾是枫原家的少爷。', 
    image: 'images/characters/fengyuan.png', 
    skills: ['万叶之一刀', '千早振', '风物之诗咏'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 54,
    base_def: 32,
    character_story: '枫原万叶是稻妻的浪人武士，曾是枫原家的少爷。他以潇洒的剑术和对自然的深刻理解而闻名，是稻妻的传奇人物。',
    constellations: ['万叶之歌', '万叶之一刀', '千早振', '风物之诗咏', '风之诗篇', '叶的传说'],
    passive_talents: ['风之诗篇', '叶的传承', '风的祝福'],
    voice_actor_cn: '李兰陵',
    voice_actor_jp: '杉田智和'
  },
  'Yoimiya': { 
    name: '宵宫', 
    element: '火元素', 
    weapon: '弓', 
    rarity: 5, 
    region: '稻妻', 
    description: '长野原家的女儿，擅长制作烟花。', 
    image: 'images/characters/xiaogong.png', 
    skills: ['弓术·炎律', '焰硝庭火舞', '琉金云间草'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1000,
    base_atk: 52,
    base_def: 30,
    character_story: '宵宫是稻妻长野原家的女儿，擅长制作烟花。她以独特的烟花制作工艺和热情的性格而闻名，是稻妻的代表性角色之一。',
    constellations: ['烟花少女', '弓术·炎律', '焰硝庭火舞', '琉金云间草', '火之热情', '烟花绽放'],
    passive_talents: ['火之热情', '烟花的祝福', '火焰的亲和'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Kamisato Ayaka': { 
    name: '神里绫华', 
    element: '冰元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '稻妻', 
    description: '稻妻神里家的大小姐，优雅的剑士。', 
    image: 'images/characters/shenli.png', 
    skills: ['神里流·霜灭', '神里流·霜灭', '神里流·霜灭'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '冰之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '神里绫华是稻妻神里家的大小姐，以优雅的剑术和高贵的气质而闻名。她精通神里流剑术，是稻妻的代表性角色之一。',
    constellations: ['神里流', '神里流·霜灭', '神里流·冰舞', '神里流·雪华', '冰元素亲和', '神里家的骄傲'],
    passive_talents: ['冰元素亲和', '神里流剑术', '雪华的祝福'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Kamisato Ayato': { 
    name: '神里绫人', 
    element: '水元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '稻妻', 
    description: '稻妻神里家的家主，心思缜密。', 
    image: 'images/characters/shenli_ren.png', 
    skills: ['神里流·镜花', '神里流·水囿', '神里流·霰步'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '神里绫人是稻妻神里家的家主，以深思熟虑的性格和高超的剑术而闻名。他是稻妻的重要人物之一。',
    constellations: ['神里流', '神里流·镜花', '神里流·水囿', '神里流·霰步', '水元素亲和', '神里家的智慧'],
    passive_talents: ['水元素亲和', '神里流剑术', '水之庇护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Yelan': { 
    name: '夜兰', 
    element: '水元素', 
    weapon: '弓', 
    rarity: 5, 
    region: '璃月', 
    description: '璃月港的情报人员，身份神秘。', 
    image: 'images/characters/yelan.png', 
    skills: ['破局矢', '渊图玲珑骰', '天网恢恢'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '夜兰是璃月港的情报人员，身份神秘。她以敏锐的洞察力和高超的情报收集能力闻名，是璃月港重要的情报来源。',
    constellations: ['情报专家', '破局矢', '渊图玲珑骰', '天网恢恢', '水元素亲和', '神秘的守护'],
    passive_talents: ['水元素亲和', '情报收集', '神秘的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Tartaglia': { 
    name: '达达利亚', 
    element: '水元素', 
    weapon: '弓', 
    rarity: 5, 
    region: '枫丹', 
    description: '执行官"公子"，擅长水元素战斗。', 
    image: 'images/characters/dadaliya.png', 
    skills: ['深渊之息', '海渊之怒', '深海之誓'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '达达利亚是愚人众执行官"公子"，以水元素之力进行战斗。他性格复杂，既是敌人也是朋友，是枫丹的重要角色。',
    constellations: ['深渊的守护者', '深渊之息', '海渊之怒', '深海之誓', '水元素亲和', '深渊的意志'],
    passive_talents: ['水元素亲和', '深渊的祝福', '深海的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Eula': { 
    name: '优菈', 
    element: '冰元素', 
    weapon: '双手剑', 
    rarity: 5, 
    region: '蒙德', 
    description: '劳伦斯家族的末裔，西风骑士团的游击队长。', 
    image: 'images/characters/youlala.png', 
    skills: ['逆焰之刃', '冰潮的涡旋', '凝浪之光剑'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['抗争的教导', '抗争的指引', '抗争的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1080,
    base_atk: 54,
    base_def: 35,
    character_story: '优菈是劳伦斯家族的末裔，西风骑士团的游击队长。她以冰元素之力进行战斗，性格坚强且富有责任感。',
    constellations: ['冰之女王', '逆焰之刃', '冰潮的涡旋', '凝浪之光剑', '冰元素亲和', '骑士的荣耀'],
    passive_talents: ['冰元素亲和', '冰之守护', '骑士的荣耀'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Shenhe': { 
    name: '申鹤', 
    element: '冰元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '璃月', 
    description: '璃月港的修行者，是留云借风真君的弟子。', 
    image: 'images/characters/shenhe.png', 
    skills: ['仪典剑术', '仰灵威·遣灵真诀', '神女遣灵真诀'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1080,
    base_atk: 52,
    base_def: 35,
    character_story: '申鹤是璃月港的修行者，是留云借风真君的弟子。她以冰元素之力进行战斗，性格冷静而坚定，拥有着强大的实力。',
    constellations: ['神女的传承', '仪典剑术', '仰灵威·遣灵真诀', '神女遣灵真诀', '冰元素亲和', '神女的守护'],
    passive_talents: ['冰元素亲和', '神女的祝福', '冰之守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Yae Miko': { 
    name: '八重神子', 
    element: '雷元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '稻妻', 
    description: '稻妻鸣神大社的宫司，雷电影的好友。', 
    image: 'images/characters/bachong.png', 
    skills: ['千早振', '天狐神火', '神樱大祓'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷王的雷电', '旧武器零件', '破损的面具', '污秽的面具'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '雷电将军的战利品', '旧武器零件', '破损的面具', '污秽的面具'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '八重神子是稻妻鸣神大社的宫司，也是雷电将军的好友。她以雷元素之力进行战斗，拥有强大的雷电力量和神秘的神力。',
    constellations: ['神子的智慧', '千早振', '天狐神火', '神樱大祓', '雷元素亲和', '神社的守护'],
    passive_talents: ['雷元素亲和', '神子的祝福', '雷电的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Klee': { 
    name: '可莉', 
    element: '火元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '提瓦特', 
    description: '魔女爱丽丝的女儿，喜欢炸鱼。', 
    image: 'images/characters/klee.png', 
    skills: ['炸弹爆炸', '烈焰冲锋', '爆炸狂欢'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1000,
    base_atk: 52,
    base_def: 30,
    character_story: '可莉是魔女爱丽丝的女儿，以爆炸魔法著称。她天真烂漫，喜欢用炸弹制造惊喜，是提瓦特世界中最受欢迎的角色之一。',
    constellations: ['爆炸专家', '炸弹爆炸', '烈焰冲锋', '爆炸狂欢', '火元素亲和', '魔法的喜悦'],
    passive_talents: ['火元素亲和', '爆炸的喜悦', '魔法的祝福'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Qiqi': { 
    name: '七七', 
    element: '冰元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '璃月', 
    description: '被仙人复活的僵尸少女，记忆力不好。', 
    image: 'images/characters/qiqi.png', 
    skills: ['普攻', '冰寒过隙', '寒病鬼差'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1080,
    base_atk: 52,
    base_def: 35,
    character_story: '七七是被仙人复活的僵尸少女，记忆力不好。她以冰元素之力进行战斗，拥有强大的治疗能力和冰霜力量。',
    constellations: ['僵尸少女', '冰寒过隙', '寒病鬼差', '冰元素亲和', '生命之源', '治疗的祝福'],
    passive_talents: ['冰元素亲和', '生命之源', '治疗的祝福'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Mona': { 
    name: '莫娜', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '蒙德', 
    description: '蒙德的占星术士，擅长使用水元素占卜。', 
    image: 'images/characters/mona.png', 
    skills: ['星象占卜', '水之预言', '命运之轮'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '莫娜是蒙德的占星术士，以水元素之力进行占卜。她以精准的预言和神秘的气质著称，是蒙德的智慧象征。',
    constellations: ['占星术', '星象占卜', '水之预言', '命运之轮', '水元素亲和', '预言的奥秘'],
    passive_talents: ['水元素亲和', '预言的智慧', '命运的指引'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '小原好美'
  },
  'Lisa': { 
    name: '丽莎', 
    element: '雷元素', 
    weapon: '法器', 
    rarity: 4, 
    region: '蒙德', 
    description: '西风教会的学者，擅长使用雷元素魔法。', 
    image: 'images/characters/lisa.png', 
    skills: ['雷电咒语', '雷击术', '雷电风暴'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 900,
    base_atk: 42,
    base_def: 26,
    character_story: '丽莎是西风教会的学者，同时也是蒙德图书馆的管理员。她以渊博的知识和强大的雷元素魔法著称，看似慵懒却隐藏着高深的实力。',
    constellations: ['雷之眷顾', '雷电咒语', '雷击术', '雷电风暴', '雷元素亲和', '智慧的传承'],
    passive_talents: ['雷元素亲和', '智慧的启迪', '魔法的精通'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '田中理恵'
  },
  'Kaeya': { 
    name: '凯亚', 
    element: '冰元素', 
    weapon: '单手剑', 
    rarity: 4, 
    region: '蒙德', 
    description: '西风骑士团的骑兵队长，擅长使用冰元素。', 
    image: 'images/characters/kaeya.png', 
    skills: ['冰霜斩击', '冰冻之刃', '寒冰领域'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '冰之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '冰之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 900,
    base_atk: 42,
    base_def: 26,
    character_story: '凯亚是西风骑士团的骑兵队长，以冰元素之力进行战斗。他性格风趣幽默，总是带着一丝神秘感，是蒙德的重要角色之一。',
    constellations: ['冰之剑', '冰霜斩击', '冰冻之刃', '寒冰领域', '冰元素亲和', '骑士的荣耀'],
    passive_talents: ['冰元素亲和', '骑士的直觉', '冰之优雅'],
    voice_actor_cn: '孙晔',
    voice_actor_jp: '鸟海浩辅'
  },
  'Amber': { 
    name: '安柏', 
    element: '火元素', 
    weapon: '弓', 
    rarity: 4, 
    region: '蒙德', 
    description: '西风骑士团的侦查骑士，擅长使用火元素弓箭。', 
    image: 'images/characters/amber.png', 
    skills: ['火焰箭', '烈焰射击', '燃烧之箭'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 900,
    base_atk: 40,
    base_def: 25,
    character_story: '安柏是西风骑士团的侦查骑士，以热情洋溢的性格和精湛的箭术著称。她是蒙德的活跃分子，热爱滑翔和冒险，总是充满活力地完成任务。',
    constellations: ['火之射手', '火焰箭', '烈焰射击', '燃烧之箭', '火元素亲和', '侦查骑士的荣耀'],
    passive_talents: ['火元素亲和', '侦查的直觉', '滑翔的技巧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Jean': { 
    name: '琴', 
    element: '风元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '蒙德', 
    description: '西风骑士团的代理团长，风元素的掌控者。', 
    image: 'images/characters/jean.png', 
    skills: ['风之剑技', '风之庇护', '风之守护'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '琴是西风骑士团的代理团长，以风元素之力守护蒙德。她正直严谨，是骑士团的中流砥柱，深受团员们的尊敬和信赖。',
    constellations: ['风之守护', '风之剑技', '风之庇护', '风之守护', '风元素亲和', '骑士团的荣耀'],
    passive_talents: ['风元素亲和', '骑士团的守护', '风之治愈'],
    voice_actor_cn: '林簌',
    voice_actor_jp: '田村由香里'
  },
  'Rosaria': { 
    name: '罗莎莉亚', 
    element: '冰元素', 
    weapon: '长柄武器', 
    rarity: 4, 
    region: '蒙德', 
    description: '西风骑士团的修女，行事风格独特。', 
    image: 'images/characters/luoshalia.png', 
    skills: ['噬罪的告解', '穿刺之冰', '终末的圣礼'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['抗争的教导', '抗争的指引', '抗争的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '罗莎莉亚是西风骑士团的修女，以冰元素之力进行战斗。她行事风格独特，看似冷漠却内心善良，是蒙德的神秘守护者。',
    constellations: ['噬罪的告解', '穿刺之冰', '终末的圣礼', '冰元素亲和', '修女的秘密', '黑暗的守护'],
    passive_talents: ['冰元素亲和', '修女的直觉', '黑暗的祝福'],
    voice_actor_cn: '张安琪',
    voice_actor_jp: '加隈亚衣'
  },
  'Sucrose': { 
    name: '砂糖', 
    element: '风元素', 
    weapon: '法器', 
    rarity: 4, 
    region: '须弥', 
    description: '阿贝多的弟子，擅长使用风元素。', 
    image: 'images/characters/sugar.png', 
    skills: ['草元素研究', '植物实验', '药剂调配'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '砂糖是阿贝多的助手，痴迷于炼金术研究。她擅长利用风元素进行实验，希望通过炼金术让世界变得更美好。',
    constellations: ['风之炼金', '草元素研究', '植物实验', '药剂调配', '风元素亲和', '炼金的奥秘'],
    passive_talents: ['风元素亲和', '炼金的直觉', '实验的精准'],
    voice_actor_cn: '谢莹',
    voice_actor_jp: '藤田咲'
  },
  'Bennett': { 
    name: '班尼特', 
    element: '火元素', 
    weapon: '单手剑', 
    rarity: 4, 
    region: '蒙德', 
    description: '班尼冒险团的团长，倒霉蛋。', 
    image: 'images/characters/bennett.png', 
    skills: ['火焰鼓舞', '火焰护盾', '火焰爆发'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 900,
    base_atk: 42,
    base_def: 26,
    character_story: '班尼特是班尼冒险团的团长，以不幸的运气和热情的性格著称。尽管总是遇到倒霉事，但他从不放弃冒险的精神，是蒙德最乐观的冒险家之一。',
    constellations: ['幸运之火', '火焰鼓舞', '火焰护盾', '火焰爆发', '火元素亲和', '冒险的意志'],
    passive_talents: ['火元素亲和', '冒险的热情', '幸运的祝福'],
    voice_actor_cn: '穆雪婷',
    voice_actor_jp: '逢坂良太'
  },
  'Fischl': { 
    name: '菲谢尔', 
    element: '雷元素', 
    weapon: '弓', 
    rarity: 5, 
    region: '枫丹', 
    description: '来自幽夜净土的菲谢尔，擅长使用雷元素。', 
    image: 'images/characters/fischl.png', 
    skills: ['雷电箭', '雷电陷阱', '雷电审判'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '菲谢尔是来自幽夜净土的断罪之皇女，与名为奥兹的夜鸦为伴。她以雷元素之力和神秘的气质著称，是枫丹的传奇人物之一。',
    constellations: ['断罪之皇女', '雷电箭', '雷电陷阱', '雷电审判', '雷元素亲和', '幽夜的守护'],
    passive_talents: ['雷元素亲和', '幽夜的智慧', '奥兹的陪伴'],
    voice_actor_cn: 'Mace',
    voice_actor_jp: '内田真礼'
  },
  'Noelle': { 
    name: '诺艾尔', 
    element: '岩元素', 
    weapon: '双手剑', 
    rarity: 4, 
    region: '蒙德', 
    description: '还未成为骑士的女仆，擅长使用岩元素防御。', 
    image: 'images/characters/noelle.png', 
    skills: ['岩石护盾', '岩石打击', '岩石屏障'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 940,
    base_atk: 45,
    base_def: 29,
    character_story: '诺艾尔是蒙德的女仆，梦想成为西风骑士团的一员。她以岩元素之力进行防御，性格温柔且充满责任感，总是尽心尽力地帮助他人。',
    constellations: ['女仆的决心', '岩石护盾', '岩石打击', '岩石屏障', '岩元素亲和', '骑士的梦想'],
    passive_talents: ['岩元素亲和', '女仆的细心', '防御的守护'],
    voice_actor_cn: '宴宁',
    voice_actor_jp: '高尾奏音'
  },
  'Razor': { 
    name: '雷泽', 
    element: '雷元素', 
    weapon: '双手剑', 
    rarity: 4, 
    region: '蒙德', 
    description: '与狼群一起长大的孩子，擅长使用雷元素攻击。', 
    image: 'images/characters/razor.png', 
    skills: ['雷电撕裂', '雷电冲击', '雷电风暴'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['自由的教导', '自由的指引', '自由的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '雷泽是与狼群一起长大的孩子，以雷元素之力进行战斗。他虽然不擅长人类的语言，但拥有敏锐的直觉和强大的战斗力，是蒙德的野性守护者。',
    constellations: ['狼之末裔', '雷电撕裂', '雷电冲击', '雷电风暴', '雷元素亲和', '狼的守护'],
    passive_talents: ['雷元素亲和', '狼的直觉', '战斗的本能'],
    voice_actor_cn: '秦且歌',
    voice_actor_jp: '内山昂辉'
  },
  'Xiangling': { 
    name: '香菱', 
    element: '火元素', 
    weapon: '长柄武器', 
    rarity: 4, 
    region: '璃月', 
    description: '璃月港的厨师，总是充满活力，擅长制作各种美食。', 
    image: 'images/characters/xiangling.png', 
    skills: ['白案功夫', '锅巴出击', '旋火轮'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '香菱是璃月港万民堂的厨师，以热情洋溢的性格和精湛的厨艺著称。她擅长将烹饪技巧融入战斗，是璃月最受欢迎的厨师之一。',
    constellations: ['烈火佳肴', '白案功夫', '锅巴出击', '旋火轮', '火元素亲和', '厨艺的巅峰'],
    passive_talents: ['火元素亲和', '烹饪的灵感', '美食的祝福'],
    voice_actor_cn: '小N',
    voice_actor_jp: '小泽亚李'
  },
  'Xingqiu': { 
    name: '行秋', 
    element: '水元素', 
    weapon: '单手剑', 
    rarity: 4, 
    region: '璃月', 
    description: '璃月港飞云商会的二少爷，喜欢阅读武侠小说。', 
    image: 'images/characters/xingqiu.png', 
    skills: ['古华剑法', '画雨笼山', '裁雨留虹'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '行秋是璃月港飞云商会的二少爷，热爱阅读武侠小说，常将书中招式融入自己的剑法。他以水元素之力战斗，展现出优雅灵动的剑技，是璃月港年轻一代中的佼佼者。',
    constellations: ['万叶飘零', '古华剑法', '画雨笼山', '裁雨留虹', '水元素亲和', '武侠的传承'],
    passive_talents: ['水元素亲和', '剑法精通', '小说灵感'],
    voice_actor_cn: '斑马',
    voice_actor_jp: '市来光弘'
  },
  'Chongyun': { 
    name: '重云', 
    element: '冰元素', 
    weapon: '双手剑', 
    rarity: 4, 
    region: '璃月', 
    description: '璃月港的驱邪方士，体内蕴含着纯阳之体。', 
    image: 'images/characters/chongyun.png', 
    skills: ['云来剑法', '重华叠霜', '云开星落'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '重云是璃月港的驱邪方士，体内蕴含着纯阳之体。他以冰元素之力进行战斗，擅长使用双手剑，是璃月的重要角色之一。',
    constellations: ['纯阳之体', '云来剑法', '重华叠霜', '云开星落', '冰元素亲和', '驱邪的意志'],
    passive_talents: ['冰元素亲和', '纯阳的守护', '驱邪的祝福'],
    voice_actor_cn: 'kinsen',
    voice_actor_jp: '下野紘'
  },
  'Ningguang': { 
    name: '凝光', 
    element: '岩元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '璃月', 
    description: '璃月港的“天权”星，掌握着璃月的经济命脉。', 
    image: 'images/characters/ningguang.png', 
    skills: ['星陨剑', '璇玑屏', '天权崩玉'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '凝光是璃月港的“天权”星，掌握着璃月的经济命脉。她以岩元素之力进行战斗，展现出强大的财富掌控能力和战斗技巧。',
    constellations: ['天权', '星陨剑', '璇玑屏', '天权崩玉', '岩元素亲和', '财富的守护'],
    passive_talents: ['岩元素亲和', '财富的守护', '经济的智慧'],
    voice_actor_cn: '杜冥鸦',
    voice_actor_jp: '大原沙耶香'
  },
  'Beidou': { 
    name: '北斗', 
    element: '雷元素', 
    weapon: '双手剑', 
    rarity: 4, 
    region: '璃月', 
    description: '璃月港“南十字”船队的船长，性格豪爽。', 
    image: 'images/characters/beidou.png', 
    skills: ['征涛快斩', '捉浪', '斫雷'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '北斗是璃月港“南十字”船队的船长，以豪爽的性格和强大的实力著称。她曾单枪匹马挑战海怪，赢得了“南十字”的称号，是璃月港的传奇人物。',
    constellations: ['南十字', '征涛快斩', '捉浪', '斫雷', '雷元素亲和', '船队的荣耀'],
    passive_talents: ['雷元素亲和', '船队的庇护', '风暴的掌控'],
    voice_actor_cn: '唐雅菁',
    voice_actor_jp: '斎藤千和'
  },
  'Xinyan': { 
    name: '辛焱', 
    element: '火元素', 
    weapon: '双手剑', 
    rarity: 4, 
    region: '璃月', 
    description: '璃月港的摇滚歌手，擅长使用火元素。', 
    image: 'images/characters/xinyan.png', 
    skills: ['摇滚的律动', '热情拂扫', '演出开始'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '辛焱是璃月港的摇滚歌手，以火元素之力进行表演和战斗。她以独特的摇滚风格和热情的性格著称，是璃月港的音乐象征。',
    constellations: ['摇滚之心', '摇滚的律动', '热情拂扫', '演出开始', '火元素亲和', '音乐的力量'],
    passive_talents: ['火元素亲和', '音乐的热情', '摇滚的力量'],
    voice_actor_cn: '王雅欣',
    voice_actor_jp: '高桥智秋'
  },
  'Yanfei': { 
    name: '烟绯', 
    element: '火元素', 
    weapon: '法器', 
    rarity: 4, 
    region: '璃月', 
    description: '璃月港的律法咨询师，半仙之体。', 
    image: 'images/characters/yanfei.png', 
    skills: ['丹火印', '丹火印·点', '业火荧煌'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '烟绯是璃月港的律法咨询师，半仙之体。她以火元素之力维护着璃月的法律秩序，同时也是一位热情洋溢的少女。',
    constellations: ['法之守护', '丹火印', '丹火印·点', '业火荧煌', '火元素亲和', '律法的智慧'],
    passive_talents: ['火元素亲和', '律法的智慧', '半仙之体'],
    voice_actor_cn: '谢莹',
    voice_actor_jp: '高桥李依'
  },
  'Gorou': { 
    name: '五郎', 
    element: '岩元素', 
    weapon: '弓', 
    rarity: 4, 
    region: '稻妻', 
    description: '海祇岛的大将，擅长使用岩元素。', 
    image: 'images/characters/gorou.png', 
    skills: ['岩之守卫', '岩之屏障', '岩之突袭'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '五郎是海祇岛的大将，以岩元素之力进行战斗。他以忠诚和勇敢著称，是海祇岛的重要守护者。',
    constellations: ['岩之守卫', '岩之屏障', '岩之突袭', '岩元素亲和', '大将的荣耀', '忠诚的守护'],
    passive_talents: ['岩元素亲和', '大将的荣耀', '忠诚的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Kujou Sara': { 
    name: '九条裟罗', 
    element: '雷元素', 
    weapon: '弓', 
    rarity: 4, 
    region: '稻妻', 
    description: '稻妻天领奉行的大将，忠于雷电将军。', 
    image: 'images/characters/jiutiao.png', 
    skills: ['鸦羽弓术', '煌煌千道镇式', '天狗食月'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '九条裟罗是稻妻天领奉行的大将，忠于雷电将军。她以雷元素之力进行战斗，拥有强大的雷电力量和忠诚的性格。',
    constellations: ['雷之守护', '鸦羽弓术', '煌煌千道镇式', '天狗食月', '雷元素亲和', '忠诚的守护'],
    passive_talents: ['雷元素亲和', '忠诚的守护', '雷电的力量'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Arataki Itto': { 
    name: '荒泷一斗', 
    element: '岩元素', 
    weapon: '双手剑', 
    rarity: 5, 
    region: '稻妻', 
    description: '稻妻“荒泷派”的头领，性格豪放。', 
    image: 'images/characters/huanglong.png', 
    skills: ['乱神之怪力', '魔像·怒目', '荒泷乱舞'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '荒泷一斗是稻妻荒泷派的头领，以岩元素之力进行战斗。他性格豪放不羁，是稻妻的传奇人物之一。',
    constellations: ['荒泷派', '乱神之怪力', '魔像·怒目', '荒泷乱舞', '岩元素亲和', '豪放的意志'],
    passive_talents: ['岩元素亲和', '豪放的意志', '荒泷派的荣耀'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Yun Jin': { 
    name: '云堇', 
    element: '岩元素', 
    weapon: '长柄武器', 
    rarity: 4, 
    region: '璃月', 
    description: '璃月港的戏曲演员，擅长唱念做打。', 
    image: 'images/characters/yunjin.png', 
    skills: ['云翰剑法', '破嶂见旌仪', '旋云开相'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '云堇是璃月港著名的戏曲演员，以精湛的唱念做打技艺闻名。她将传统戏曲与岩元素力量相结合，创造出独特的战斗风格。',
    constellations: ['戏韵流芳', '云翰剑法', '破嶂见旌仪', '旋云开相', '岩元素亲和', '戏曲的传承'],
    passive_talents: ['岩元素亲和', '戏曲的韵律', '舞台的掌控'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Shikanoin Heizou': { 
    name: '鹿野院平藏', 
    element: '风元素', 
    weapon: '法器', 
    rarity: 4, 
    region: '稻妻', 
    description: '稻妻天领奉行的侦探，聪明机智。', 
    image: 'images/characters/luye.png', 
    skills: ['心朝乂安', '装卦·明察', '秘策·穷理'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '鹿野院平藏是稻妻天领奉行的侦探，以风元素之力进行推理和战斗。他聪明机智，擅长破解各种疑难案件。',
    constellations: ['侦探的智慧', '心朝乂安', '装卦·明察', '秘策·穷理', '风元素亲和', '推理的奥秘'],
    passive_talents: ['风元素亲和', '侦探的直觉', '推理的智慧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Kuki Shinobu': { 
    name: '久岐忍', 
    element: '雷元素', 
    weapon: '单手剑', 
    rarity: 4, 
    region: '稻妻', 
    description: '稻妻“荒泷派”的二把手，冷静理智。', 
    image: 'images/characters/jiuqi.png', 
    skills: ['阿波卡利斯的裁决', '护法之誓', '净土裁断'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '久岐忍是稻妻“荒泷派”的二把手，以雷元素之力进行战斗。她冷静理智，是荒泷派的重要支柱。',
    constellations: ['荒泷派二把手', '阿波卡利斯的裁决', '护法之誓', '净土裁断', '雷元素亲和', '理智的守护'],
    passive_talents: ['雷元素亲和', '理智的守护', '荒泷派的荣耀'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Collei': { 
    name: '柯莱', 
    element: '草元素', 
    weapon: '弓', 
    rarity: 4, 
    region: '须弥', 
    description: '须弥教令院的学徒，曾是蒙德的孤儿。', 
    image: 'images/characters/keli.png', 
    skills: ['蓄力箭', '苑田瞬发', '约定的花海'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '柯莱是须弥教令院的学徒，曾是蒙德的孤儿。她以草元素之力进行战斗，拥有强大的草元素力量和坚韧的意志。',
    constellations: ['草之学徒', '蓄力箭', '苑田瞬发', '约定的花海', '草元素亲和', '学徒的成长'],
    passive_talents: ['草元素亲和', '学徒的成长', '草之守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Dori': { 
    name: '多莉', 
    element: '雷元素', 
    weapon: '双手剑', 
    rarity: 4, 
    region: '须弥', 
    description: '须弥的商人，经营着各种奇特商品。', 
    image: 'images/characters/duoli.png', 
    skills: ['金流弹反', '神奇的灯中幽精', '一千零一夜'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '多莉是须弥著名的商人，以经营各种奇特商品而闻名。她以雷元素之力进行战斗，拥有强大的雷电力量和敏锐的商业头脑。',
    constellations: ['商人的智慧', '金流弹反', '神奇的灯中幽精', '一千零一夜', '雷元素亲和', '商业的奥秘'],
    passive_talents: ['雷元素亲和', '商业的智慧', '财富的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Tighnari': { 
    name: '提纳里', 
    element: '草元素', 
    weapon: '弓', 
    rarity: 5, 
    region: '须弥', 
    description: '须弥教令院的学者，擅长植物学。', 
    image: 'images/characters/tainali.png', 
    skills: ['藏弓·序章', '识藏之花', '造生之种'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '提纳里是须弥教令院的学者，擅长植物学。他以草元素之力进行战斗，拥有丰富的植物学知识和强大的草元素力量。',
    constellations: ['植物学家', '藏弓·序章', '识藏之花', '造生之种', '草元素亲和', '植物的奥秘'],
    passive_talents: ['草元素亲和', '植物的知识', '草之守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Cyno': { 
    name: '赛诺', 
    element: '雷元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '须弥', 
    description: '须弥教令院的大风纪官，公正严明。', 
    image: 'images/characters/saino.png', 
    skills: ['秘仪·律渊渡魂', '秘仪·迷踪之砂', '秘仪·真数谶言'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '赛诺是须弥教令院的大风纪官，以雷元素之力维护教令院的秩序。他公正严明，是须弥智慧的守护者之一。',
    constellations: ['大风纪官', '秘仪·律渊渡魂', '秘仪·迷踪之砂', '秘仪·真数谶言', '雷元素亲和', '公正的裁决'],
    passive_talents: ['雷元素亲和', '公正的裁决', '智慧的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Nilou': { 
    name: '妮露', 
    element: '水元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '须弥', 
    description: '须弥大巴扎的舞者，擅长水元素舞蹈。', 
    image: 'images/characters/nilu.png', 
    skills: ['普攻', '水环', '翩转惊鸿'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '妮露是须弥大巴扎的舞者，以水元素舞蹈著称。她的舞蹈优美动人，是须弥的文化象征之一。',
    constellations: ['水之舞者', '水环', '翩转惊鸿', '水元素亲和', '舞蹈的奥秘', '水之祝福'],
    passive_talents: ['水元素亲和', '舞蹈的奥秘', '水之祝福'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Candace': { 
    name: '坎蒂丝', 
    element: '水元素', 
    weapon: '长柄武器', 
    rarity: 4, 
    region: '须弥', 
    description: '须弥阿弥村的守护者，擅长使用水元素。', 
    image: 'images/characters/candace.png', 
    skills: ['水之契约', '水之谈判', '水之调和'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '坎蒂丝是须弥阿弥村的守护者，以水元素之力守护着村庄的和平。她拥有强大的水元素力量和坚定的意志，是阿弥村的重要支柱。',
    constellations: ['水之守护', '水之契约', '水之谈判', '水之调和', '水元素亲和', '守护者的荣耀'],
    passive_talents: ['水元素亲和', '守护者的荣耀', '水之祝福'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Dehya': { 
    name: '迪希雅', 
    element: '火元素', 
    weapon: '双手剑', 
    rarity: 5, 
    region: '须弥', 
    description: '须弥的佣兵，性格豪爽。', 
    image: 'images/characters/dixiya.png', 
    skills: ['普攻', '炎之舞', '烈焰焚天'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '迪希雅是须弥的佣兵，性格豪爽。她以火元素之力进行战斗，拥有强大的战斗力和坚定的意志。',
    constellations: ['佣兵的荣耀', '炎之舞', '烈焰焚天', '火元素亲和', '战斗的意志', '豪爽的性格'],
    passive_talents: ['火元素亲和', '战斗的意志', '豪爽的性格'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Wanderer': { 
    name: '流浪者', 
    element: '风元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '须弥', 
    description: '原愚人众执行官第六席“散兵”，现为流浪者。', 
    image: 'images/characters/sanbing.png', 
    skills: ['普攻', '空居·虚铃', '正机之神'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '流浪者是原愚人众执行官第六席“散兵”，现为流浪者。他以风元素之力进行战斗，拥有强大的风元素力量和神秘的身世背景。',
    constellations: ['流浪者', '空居·虚铃', '正机之神', '风元素亲和', '自由之风', '流浪者的意志'],
    passive_talents: ['风元素亲和', '自由之风', '流浪者的意志'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Faruzan': { 
    name: '珐露珊', 
    element: '风元素', 
    weapon: '弓', 
    rarity: 4, 
    region: '须弥', 
    description: '200年前须弥教令院的学者，擅长风元素。', 
    image: 'images/characters/falushan.png', 
    skills: ['普攻', '风涡弹', '风息激荡'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '血玉之枝', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '珐露珊是200年前须弥教令院的学者，以风元素之力进行战斗。她拥有渊博的知识和强大的风元素力量，是须弥的智慧象征。',
    constellations: ['风之学者', '风涡弹', '风息激荡', '风元素亲和', '智慧的传承', '风之奥秘'],
    passive_talents: ['风元素亲和', '智慧的传承', '风之奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Alhaitham': { 
    name: '艾尔海森', 
    element: '草元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '须弥', 
    description: '须弥教令院的学者，冷静理智。', 
    image: 'images/characters/aierhaisen.png', 
    skills: ['普攻', '识藏之花', '造生之种'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '艾尔海森是须弥教令院的学者，以草元素之力进行战斗。他冷静理智，是须弥智慧的象征。',
    constellations: ['草之学者', '识藏之花', '造生之种', '草元素亲和', '智慧的传承', '草之奥秘'],
    passive_talents: ['草元素亲和', '智慧的传承', '草之奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Kaveh': { 
    name: '卡维', 
    element: '草元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '须弥', 
    description: '须弥教令院的建筑师，性格温和。', 
    image: 'images/characters/kayi.png', 
    skills: ['普攻', '识藏之花', '造生之种'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '卡维是须弥教令院的建筑师，以草元素之力进行创作。他性格温和，擅长设计各种建筑，是须弥教令院的重要成员。',
    constellations: ['草之建筑师', '识藏之花', '造生之种', '草元素亲和', '建筑的智慧', '设计的奥秘'],
    passive_talents: ['草元素亲和', '建筑的智慧', '设计的灵感'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Baizhu': { 
    name: '白术', 
    element: '草元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '璃月', 
    description: '璃月港“不卜庐”的老板，医术高明。', 
    image: 'images/characters/baizhu.png', 
    skills: ['行针步引', '愈气全形', '灵草愈疗'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 1080,
    base_atk: 52,
    base_def: 35,
    character_story: '白术是璃月港“不卜庐”的老板，医术高明。他性格温和，擅长使用草元素进行治疗，是璃月港的重要医疗力量。',
    constellations: ['不卜庐的老板', '行针步引', '愈气全形', '灵草愈疗', '草元素亲和', '医术的传承'],
    passive_talents: ['草元素亲和', '医术的传承', '生命的守护'],
    voice_actor_cn: '秦且歌',
    voice_actor_jp: '关智一'
  },
  'Yaoyao': { 
    name: '瑶瑶', 
    element: '草元素', 
    weapon: '长柄武器', 
    rarity: 4, 
    region: '璃月', 
    description: '萍姥姥最小的弟子，擅长使用草元素治疗。', 
    image: 'images/characters/yaoyao.png', 
    skills: ['草药调配', '治疗之术', '生命之源'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 960,
    base_atk: 46,
    base_def: 30,
    character_story: '瑶瑶是璃月的药师，擅长使用草元素进行治疗。她是萍姥姥最小的弟子，继承了师父的医术精髓。',
    constellations: ['草之守护', '草药调配', '治疗之术', '生命之源', '草元素亲和', '医者仁心'],
    passive_talents: ['草元素亲和', '治疗之术', '生命之源'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '茅野爱衣'
  },
  'Mika': { 
    name: '米卡', 
    element: '冰元素', 
    weapon: '弓', 
    rarity: 4, 
    region: '须弥', 
    description: '须弥的侦察兵，擅长冰元素。', 
    image: 'images/characters/mika.png', 
    skills: ['普攻', '冰之箭', '冰雾花之舞'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['智慧的教导', '智慧的指引', '智慧的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '米卡是须弥的侦察兵，擅长使用冰元素进行侦察和战斗。她以敏捷的身手和精准的箭术著称。',
    constellations: ['冰之侦察', '冰之箭', '冰雾花之舞', '冰元素亲和', '寒风之影', '雪地追踪'],
    passive_talents: ['冰元素亲和', '冰之敏捷', '雪地追踪'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Lynette': { 
    name: '琳妮特', 
    element: '风元素', 
    weapon: '单手剑', 
    rarity: 4, 
    region: '枫丹', 
    description: '枫丹的魔术师助手，擅长风元素。', 
    image: 'images/characters/linniete.png', 
    skills: ['普攻', '风之舞', '风息激荡'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '琳妮特是枫丹著名魔术师林尼的助手，以优雅的风元素技巧和神秘的气质著称。她总是默默支持着林尼的表演，是魔术师组合中不可或缺的一部分。',
    constellations: ['风之幻影', '风之舞', '风息激荡', '风元素亲和', '魔术的奥秘', '助手的守护'],
    passive_talents: ['风元素亲和', '魔术的敏捷', '助手的专注'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Lyney': { 
    name: '林尼', 
    element: '火元素', 
    weapon: '弓', 
    rarity: 5, 
    region: '枫丹', 
    description: '枫丹的魔术师，擅长火元素魔法。', 
    image: 'images/characters/linni.png', 
    skills: ['普攻', '火焰魔术', '烈焰表演'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '林尼是枫丹著名的魔术师，以火元素之力进行表演和战斗。他与妹妹琳妮特一起，以精彩的魔术表演闻名枫丹，是枫丹舞台上的焦点人物。',
    constellations: ['魔术大师', '火焰魔术', '烈焰表演', '火元素亲和', '舞台的焦点', '魔术的奥秘'],
    passive_talents: ['火元素亲和', '魔术的灵巧', '舞台的掌控'],
    voice_actor_cn: 'kinsen',
    voice_actor_jp: '下野紘'
  },
  'Freminet': { 
    name: '菲米尼', 
    element: '冰元素', 
    weapon: '双手剑', 
    rarity: 4, 
    region: '枫丹', 
    description: '枫丹的潜水员，擅长冰元素。', 
    image: 'images/characters/feimini.png', 
    skills: ['普攻', '冰之舞', '冰雾花之舞'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '菲米尼是枫丹的潜水员，以冰元素之力进行潜水和战斗。他擅长在水下探索和战斗，是枫丹水下探索的专家。',
    constellations: ['冰之潜水', '冰之舞', '冰雾花之舞', '冰元素亲和', '水下探索', '潜水专家'],
    passive_talents: ['冰元素亲和', '水下探索', '潜水专家'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Charlotte': { 
    name: '夏洛蒂', 
    element: '冰元素', 
    weapon: '法器', 
    rarity: 4, 
    region: '枫丹', 
    description: '枫丹的记者，以水元素之力记录真相。', 
    image: 'images/characters/xialuodi.png', 
    skills: ['笔锋流转', '真相探寻', '头条新闻'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '夏洛蒂是枫丹的记者，以水元素之力记录真相。她以敏锐的洞察力和公正的报道著称，是枫丹的真相守护者。',
    constellations: ['真相探寻', '笔锋流转', '头条新闻', '水元素亲和', '记者的直觉', '真相的守护'],
    passive_talents: ['水元素亲和', '记者的直觉', '真相的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Navia': { 
    name: '娜维娅', 
    element: '岩元素', 
    weapon: '双手剑', 
    rarity: 5, 
    region: '枫丹', 
    description: '枫丹的大小姐，执掌刺玫会。', 
    image: 'images/characters/navia.png', 
    skills: ['蔷薇剑舞', '蔷薇的誓言', '玫瑰之雨'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '娜维娅是枫丹的大小姐，执掌刺玫会。她以岩元素之力守护枫丹的秩序，性格优雅且充满责任感，是枫丹的重要守护者。',
    constellations: ['蔷薇剑舞', '蔷薇的誓言', '玫瑰之雨', '岩元素亲和', '刺玫会的荣耀', '优雅的守护'],
    passive_talents: ['岩元素亲和', '刺玫会的守护', '优雅的意志'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Chevreuse': { 
    name: '夏沃蕾', 
    element: '火元素', 
    weapon: '弓', 
    rarity: 4, 
    region: '枫丹', 
    description: '枫丹的检察官，擅长使用草元素。', 
    image: 'images/characters/xiawolai.png', 
    skills: ['草元素侦查', '草元素追踪', '草元素分析'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '夏沃蕾是枫丹的检察官，以草元素之力维护正义。她严谨公正，是枫丹法律体系的重要支柱。',
    constellations: ['草元素侦查', '草元素追踪', '草元素分析', '草元素亲和', '检察官的智慧', '正义的守护'],
    passive_talents: ['草元素亲和', '检察官的直觉', '正义的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Chiori': { 
    name: '千织', 
    element: '岩元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '枫丹', 
    description: '枫丹的服装设计师，擅长使用岩元素。', 
    image: 'images/characters/qianzhi.png', 
    skills: ['岩之编织', '岩之设计', '岩之创意'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '千织是枫丹著名的服装设计师，以岩元素之力进行创作。她将岩石的坚韧与服装的柔美完美结合，创造出独特的时尚风格。',
    constellations: ['岩之编织', '岩之设计', '岩之创意', '岩元素亲和', '时尚的灵感', '设计的奥秘'],
    passive_talents: ['岩元素亲和', '时尚的灵感', '设计的奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Clorinde': { 
    name: '克洛琳德', 
    element: '雷元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '枫丹', 
    description: '枫丹的审判官，以雷元素之力执行正义。', 
    image: 'images/characters/keluolinde.png', 
    skills: ['雷鸣回响', 'Shamshir的裁决', '誓约之眼'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '克洛琳德是枫丹的审判官，以雷元素之力执行正义。她以公正严明的审判和强大的雷电力量著称，是枫丹法律体系的重要支柱。',
    constellations: ['雷之审判', '雷鸣回响', 'Shamshir的裁决', '誓约之眼', '雷元素亲和', '正义的守护'],
    passive_talents: ['雷元素亲和', '正义的守护', '审判的智慧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Sigewinne': { 
    name: '希格雯', 
    element: '水元素', 
    weapon: '弓箭', 
    rarity: 5, 
    region: '枫丹', 
    description: '枫丹的医疗官，擅长使用水元素治疗。', 
    image: 'images/characters/xigewen.png', 
    skills: ['水之治疗', '水之复苏', '水之再生'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '希格雯是枫丹的医疗官，以水元素之力进行治疗。她温柔善良，是枫丹人民健康的守护者。',
    constellations: ['水之治疗', '水之复苏', '水之再生', '水元素亲和', '医疗的守护', '生命的祝福'],
    passive_talents: ['水元素亲和', '医疗的智慧', '生命的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Arlecchino': { 
    name: '阿蕾奇诺', 
    element: '火元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '枫丹', 
    description: '枫丹的执行官，以火元素之力执行法律。', 
    image: 'images/characters/aleichuo.png', 
    skills: ['烈焰之刃', '烈焰燃烧', '烈焰审判'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '阿蕾奇诺是枫丹的执行官，以火元素之力执行法律。她性格冷酷，是枫丹法律体系的重要执行者，拥有强大的火焰力量和坚定的意志。',
    constellations: ['烈焰之刃', '烈焰燃烧', '烈焰审判', '火元素亲和', '执行官的荣耀', '法律的守护'],
    passive_talents: ['火元素亲和', '执行官的荣耀', '法律的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Neuvillette': { 
    name: '那维莱特', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '枫丹', 
    description: '枫丹的最高审判官，原初的那维莱特，掌握水元素力量。', 
    image: 'images/characters/naweilaite.png', 
    skills: ['如水流转寻平衡', '泪之誓约', '潮之归返'], 
    ascension_materials: ['浮涌之潮碎屑', '浮涌之潮断片', '浮涌之潮块', '浮涌之潮', '流光星髓', '越洋珍珠', '越洋碎块', '异色谱晶'], 
    talent_materials: ['公正的教导', '公正的指引', '公正的哲学', '永恒琥珀', '越洋珍珠', '越洋碎块', '异色谱晶'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '那维莱特是枫丹的最高审判官，原初的那维莱特，掌握着水元素的本源力量。他以公正严明的审判和深厚的智慧著称，是枫丹秩序的维护者。',
    constellations: ['原初的审判', '如水流转寻平衡', '泪之誓约', '潮之归返', '水元素亲和', '审判的智慧'],
    passive_talents: ['水元素亲和', '审判的智慧', '秩序的守护'],
    voice_actor_cn: '彭博',
    voice_actor_jp: '神谷浩史'
  },
  'Wriothesley': { 
    name: '莱欧斯利', 
    element: '冰元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '枫丹', 
    description: '梅洛彼得堡的管理者，以冰元素之力维护秩序。', 
    image: 'images/characters/laiousili.png', 
    skills: ['重拳制裁', '寒狱冰牢', '终审判决'], 
    ascension_materials: ['哀叙冰玉碎屑', '哀叙冰玉断片', '哀叙冰玉块', '哀叙冰玉', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '极寒之核', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '莱欧斯利是梅洛彼得堡的管理者，以冰元素之力维护秩序。他以冷静理智的性格和强大的冰元素力量著称，是枫丹秩序的重要维护者。',
    constellations: ['冰之审判', '重拳制裁', '寒狱冰牢', '终审判决', '冰元素亲和', '秩序的守护'],
    passive_talents: ['冰元素亲和', '秩序的守护', '审判的智慧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Xianyun': { 
    name: '闲云', 
    element: '风元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '璃月', 
    description: '璃月港的隐士，擅长使用风元素。', 
    image: 'images/characters/xianyun.png', 
    skills: ['风之隐匿', '风之飘逸', '风之自由'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['繁荣的教导', '繁荣的指引', '繁荣的哲学', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '闲云是璃月港的神秘隐士，以风元素之力进行战斗。她性格淡泊名利，喜欢在山林间隐居修行，是璃月的智慧象征。',
    constellations: ['风之隐士', '风之隐匿', '风之飘逸', '风之自由', '风元素亲和', '山林的守护'],
    passive_talents: ['风元素亲和', '山林的智慧', '风之祝福'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Gaming': { 
    name: '嘉明', 
    element: '火元素', 
    weapon: '双手剑', 
    rarity: 4, 
    region: '枫丹', 
    description: '枫丹的工程师，擅长使用火元素。', 
    image: 'images/characters/jiaming.png', 
    skills: ['火之工程', '火之设计', '火之制造'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['正义的教导', '正义的指引', '正义的哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 920,
    base_atk: 44,
    base_def: 28,
    character_story: '嘉明是枫丹的工程师，以火元素之力进行创作。他擅长设计各种机械装置，是枫丹工程领域的杰出人才。',
    constellations: ['火之工程', '火之设计', '火之制造', '火元素亲和', '工程师的智慧', '创造的奥秘'],
    passive_talents: ['火元素亲和', '工程师的智慧', '创造的灵感'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  'Sangonomiya Kokomi': { 
    name: '珊瑚宫心海', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '稻妻', 
    description: '稻妻海祇岛的“现人神巫女”，擅长谋略。', 
    image: 'images/characters/xinhai.png', 
    skills: ['水有常形', '海人化羽', '海月之誓'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '水之滴', '净水之心', '纯水之愿', '浓缩树脂'], 
    talent_materials: ['雷电的教导', '雷电的指引', '雷电的哲学', '芙宁娜的战利品', '净水之心', '纯水之愿', '浓缩树脂'],
    base_hp: 1050,
    base_atk: 50,
    base_def: 35,
    character_story: '珊瑚宫心海是稻妻海祇岛的“现人神巫女”，以水元素之力守护海祇岛的和平。她擅长谋略，是海祇岛的智慧象征。',
    constellations: ['海祇之心', '水有常形', '海人化羽', '海月之誓', '水元素亲和', '谋略的智慧'],
    passive_talents: ['水元素亲和', '谋略的智慧', '海祇的守护'],
    voice_actor_cn: '龟娘',
    voice_actor_jp: '三森铃子'
  },
  'Mavica': { 
    name: '玛薇卡', 
    element: '火元素', 
    weapon: '双手剑', 
    rarity: 5, 
    region: '纳塔', 
    description: '新晋神明，输出能力和对战斗节奏的掌控力非常强劲，是当前版本最强的站场主C之一。', 
    image: 'images/characters/mavica.png', 
    skills: ['普攻', '火焰之怒', '烈焰之裁'], 
    ascension_materials: ['燃愿玛瑙碎屑', '燃愿玛瑙断片', '燃愿玛瑙块', '燃愿玛瑙', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['火之教导', '火之指引', '火之哲学', '炎之花', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '玛薇卡是纳塔的新晋神明，以火元素之力进行战斗。她拥有强大的输出能力和对战斗节奏的掌控力，是当前版本最强的站场主C之一。',
    constellations: ['火焰之怒', '烈焰之裁', '火元素亲和', '神明的祝福', '战斗的节奏', '火焰的掌控'],
    passive_talents: ['火元素亲和', '战斗的节奏', '火焰的掌控'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '希诺宁': { 
    name: '希诺宁', 
    element: '岩元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '纳塔', 
    description: '纳塔有名的铸造师，由于有着高超的技艺对她崇拜有加，纷纷从各地慕名而来。', 
    image: 'images/characters/xinuoning.png', 
    skills: ['焮火铸魂', '焮火技艺', '焮火守护'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['豹猫座', '豹猫座', '豹猫座', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '希诺宁是纳塔有名的铸造师，以岩元素之力打造出无数精良武器。她的技艺高超，吸引了来自各地的崇拜者，是纳塔锻造业的传奇人物。',
    constellations: ['焮火铸魂', '焮火技艺', '焮火守护', '岩元素亲和', '铸造大师', '炉火纯青'],
    passive_talents: ['岩元素亲和', '锻造精通', '炉火的祝福'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '基尼奇': { 
    name: '基尼奇', 
    element: '草元素', 
    weapon: '双手剑', 
    rarity: 5, 
    region: '纳塔', 
    description: '悬木人是部落中有名的猎龙者，在人与龙和洽共生的纳塔，猎龙人从诞生之初就无法获得所有人的理解。', 
    image: 'images/characters/jiniqi.png', 
    skills: ['回火之狩', '幻瑞兽座', '幻瑞兽座'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['幻瑞兽座', '幻瑞兽座', '幻瑞兽座', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '基尼奇是纳塔悬木人部落的猎龙者，以草元素之力与巨龙战斗。在人与龙共生的纳塔，他的存在充满了争议，但他始终坚持自己的道路。',
    constellations: ['回火之狩', '幻瑞兽座', '草元素亲和', '猎龙者的荣耀', '自然的守护', '龙血的传承'],
    passive_talents: ['草元素亲和', '猎龙的直觉', '自然的庇护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '玛拉妮': { 
    name: '玛拉妮', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '纳塔', 
    description: '作为流泉之众新生代的一员，玛拉妮的名气早就传遍了纳塔，在她规划的路线上，可以欣赏到火山爆发的绚丽景色。', 
    image: 'images/characters/malani.png', 
    skills: ['哗啦啦逐浪客', '浪海豹座', '浪海豹座'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['浪海豹座', '浪海豹座', '浪海豹座', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '玛拉妮是流泉之众新生代的一员，以水元素之力进行战斗。她以火山爆发的绚丽景色为背景，展现出了独特的战斗风格和魅力。',
    constellations: ['流泉之众', '哗啦啦逐浪客', '浪海豹座', '水元素亲和', '火山的祝福', '浪花的守护'],
    passive_talents: ['水元素亲和', '浪花的祝福', '火山的守护'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '欧洛伦': { 
    name: '欧洛伦', 
    element: '雷元素', 
    weapon: '弓箭', 
    rarity: 5, 
    region: '纳塔', 
    description: '欧洛伦是纳塔烟谜主部落的成员，是纳塔的烟蝠。', 
    image: 'images/characters/ouluolun.png', 
    skills: ['深黯的谜烟', '夜蝠座', '夜蝠座'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['夜蝠座', '夜蝠座', '夜蝠座', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '欧洛伦是纳塔烟谜主部落的成员，以雷元素之力进行战斗。他拥有神秘的烟蝠能力，是纳塔的传奇人物。',
    constellations: ['烟谜主', '深黯的谜烟', '夜蝠座', '雷元素亲和', '烟雾的守护', '谜烟的奥秘'],
    passive_talents: ['雷元素亲和', '烟雾的守护', '谜烟的奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '恰斯卡': { 
    name: '恰斯卡', 
    element: '风元素', 
    weapon: '弓箭', 
    rarity: 5, 
    region: '纳塔', 
    description: '恰斯卡是花羽会部落的成员，各部落间远近闻名的调停人。', 
    image: 'images/characters/qiasika.png', 
    skills: ['巡宇翦定', '神鹫座', '神鹫座'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['神鹫座', '神鹫座', '神鹫座', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '恰斯卡是花羽会部落的成员，以风元素之力进行战斗。她以调停人身份闻名，是纳塔各部落之间的和平使者。',
    constellations: ['花羽会', '巡宇翦定', '神鹫座', '风元素亲和', '神鹫的守护', '调停者的智慧'],
    passive_talents: ['风元素亲和', '神鹫的守护', '调停者的智慧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '伊安珊': { 
    name: '伊安珊', 
    element: '雷元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '纳塔', 
    description: '伊安珊是沃陆之邦的战士，运动教练是她的本职工作。', 
    image: 'images/characters/ianshan.png', 
    skills: ['熔石百炼', '牨龙座', '牨龙座'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['牨龙座', '牨龙座', '牨龙座', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '伊安珊是沃陆之邦的战士，以雷元素之力进行战斗。她以运动教练的身份为职业，拥有强大的战斗力。',
    constellations: ['沃陆之邦', '熔石百炼', '牨龙座', '雷元素亲和', '战士的荣耀', '力量的传承'],
    passive_talents: ['雷元素亲和', '战士的荣耀', '力量的传承'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '卡齐娜': { 
    name: '卡齐娜', 
    element: '岩元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '纳塔', 
    description: '斑金矿朴，纳茨卡延的年轻勇士。', 
    image: 'images/characters/kazina.png', 
    skills: ['斑金矿朴', '鼠兔座', '鼠兔座'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['鼠兔座', '鼠兔座', '鼠兔座', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '卡齐娜是纳塔纳茨卡延的年轻勇士，以岩元素之力进行战斗。她拥有强大的力量和坚韧的意志，是纳塔地区的杰出战士。',
    constellations: ['纳茨卡延', '斑金矿朴', '鼠兔座', '岩元素亲和', '矿石的祝福', '勇士的荣耀'],
    passive_talents: ['岩元素亲和', '矿石的祝福', '勇士的荣耀'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '茜特菈莉': { 
    name: '茜特菈莉', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '纳塔', 
    description: '纳塔米克特兰的观星者，擅长使用水元素。', 
    image: 'images/characters/chestina.png', 
    skills: ['水元素攻击', '水元素技能', '水元素防御'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['米克特兰的教导', '米克特兰的指引', '米克特兰的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '茜特菈莉是纳塔米克特兰的观星者，以水元素之力进行战斗。她精通天文观测和水元素的运用，是纳塔地区的智慧象征。',
    constellations: ['米克特兰', '水元素攻击', '水元素技能', '水元素防御', '水之智慧', '星辰的守护'],
    passive_talents: ['水元素亲和', '星辰的祝福', '水之智慧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '瓦雷莎': { 
    name: '瓦雷莎', 
    element: '雷元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '纳塔', 
    description: '纳塔沃陆之邦的中坚战士，擅长使用岩元素。', 
    image: 'images/characters/valesha.png', 
    skills: ['岩元素攻击', '岩元素技能', '岩元素防御'], 
    ascension_materials: ['坚牢黄玉碎屑', '坚牢黄玉断片', '坚牢黄玉块', '坚牢黄玉', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['沃陆之邦的教导', '沃陆之邦的指引', '沃陆之邦的哲学', '岩之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '瓦雷莎是纳塔沃陆之邦的中坚战士，以雷元素之力进行战斗。她以岩元素为辅助，展现出强大的战斗能力。',
    constellations: ['沃陆之邦', '岩元素攻击', '岩元素技能', '岩元素防御', '雷之守护', '战士的荣耀'],
    passive_talents: ['雷元素亲和', '岩元素辅助', '战士的荣耀'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '伊法': { 
    name: '伊法', 
    element: '风元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '纳塔', 
    description: '纳塔特拉洛坎的兽医，擅长使用风元素。', 
    image: 'images/characters/iffa.png', 
    skills: ['风元素攻击', '风元素技能', '风元素防御'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['特拉洛坎的教导', '特拉洛坎的指引', '特拉洛坎的哲学', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '伊法是纳塔特拉洛坎的兽医，以风元素之力进行战斗。她精通动物医学和风元素的运用，是纳塔地区的医疗专家。',
    constellations: ['特拉洛坎', '风元素攻击', '风元素技能', '风元素防御', '风之守护', '兽医的智慧'],
    passive_talents: ['风元素亲和', '风之守护', '兽医的智慧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '爱诺': { 
    name: '爱诺', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 4, 
    region: '挪德卡莱', 
    description: '叮铃哐当蛋卷工坊的主人，擅长制造各种机械，重新拼装了伊涅芙。', 
    image: 'images/characters/ainuo.png', 
    skills: ['机械制造', '家政机器人', '元素操控'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['挪德卡莱的教导', '挪德卡莱的指引', '挪德卡莱的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 960,
    base_atk: 46,
    base_def: 30,
    character_story: '爱诺是挪德卡莱叮铃哐当蛋卷工坊的主人，擅长制造各种机械，重新拼装了伊涅芙。她以水元素之力进行战斗，展现出独特的机械与元素结合的战斗风格。',
    constellations: ['机械之心', '家政机器人', '元素操控', '水元素亲和', '机械的祝福', '创造的奥秘'],
    passive_talents: ['水元素亲和', '机械的祝福', '创造的奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '伊涅芙': { 
    name: '伊涅芙', 
    element: '雷元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '挪德卡莱', 
    description: '首位空月之歌系列角色，带来全新反应——月感电。', 
    image: 'images/characters/yinefu.png', 
    skills: ['月感电', '空月之歌', '元素反应'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['空月的教导', '空月的指引', '空月的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '伊涅芙是首位空月之歌系列角色，带来全新反应——月感电。她以雷元素之力进行战斗，展现出独特的战斗风格和魅力。',
    constellations: ['空月之歌', '月感电', '元素反应', '雷元素亲和', '月之祝福', '空月的奥秘'],
    passive_talents: ['雷元素亲和', '月之祝福', '空月的奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '雅珂达': { 
    name: '雅珂达', 
    element: '风元素', 
    weapon: '弓箭', 
    rarity: 5, 
    region: '挪德卡莱', 
    description: '叮呤哐啷蛋卷工坊的新角色，风格新颖独特。', 
    image: 'images/characters/yakeda.png', 
    skills: ['风元素攻击', '风元素技能', '风元素防御'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['雅珂达的教导', '雅珂达的指引', '雅珂达的哲学', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '雅珂达是挪德卡莱叮呤哐啷蛋卷工坊的新角色，以风元素之力进行战斗。她以新颖独特的风格和强大的风元素力量著称。',
    constellations: ['风之舞者', '风元素攻击', '风元素技能', '风元素防御', '风之祝福', '风之奥秘'],
    passive_talents: ['风元素亲和', '风之祝福', '风之奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '杜林': { 
    name: '杜林', 
    element: '火元素', 
    weapon: '单手剑', 
    rarity: 5, 
    region: '挪德卡莱', 
    description: '化形后的形象非常优秀帅气，符合剧情塑造。', 
    image: 'images/characters/dulin.png', 
    skills: ['岩元素攻击', '岩元素技能', '岩元素防御'], 
    ascension_materials: ['自在松石碎屑', '自在松石断片', '自在松石块', '自在松石', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['杜林的教导', '杜林的指引', '杜林的哲学', '东风之翎', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '杜林是挪德卡莱的化形者，以火元素之力进行战斗。他以优秀帅气的形象和强大的战斗力著称，是挪德卡莱的传奇人物。',
    constellations: ['化形者', '岩元素攻击', '岩元素技能', '岩元素防御', '火之祝福', '化形的奥秘'],
    passive_talents: ['火元素亲和', '化形的祝福', '火之奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '菲林斯': { 
    name: '菲林斯', 
    element: '雷元素', 
    weapon: '长柄武器', 
    rarity: 5, 
    region: '挪德卡莱', 
    description: '执灯人的首领，雷系神之眼，奈芙尔伏尼奇商会阵营。', 
    image: 'images/characters/feilinsi.png', 
    skills: ['雷元素攻击', '雷元素技能', '雷元素防御'], 
    ascension_materials: ['雷霆数珠碎屑', '雷霆数珠断片', '雷霆数珠块', '雷霆数珠', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['执灯人的教导', '执灯人的指引', '执灯人的哲学', '雷之心', '史莱姆凝液', '史莱姆清', '史莱姆原浆'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '菲林斯是挪德卡莱执灯人的首领，以雷元素之力进行战斗。他是奈芙尔伏尼奇商会阵营的重要人物，拥有强大的雷元素力量和领导才能。',
    constellations: ['执灯人', '雷元素攻击', '雷元素技能', '雷元素防御', '雷之守护', '执灯人的智慧'],
    passive_talents: ['雷元素亲和', '雷之守护', '执灯人的智慧'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '奈芙尔': { 
    name: '奈芙尔', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '挪德卡莱', 
    description: '伏尼奇商会阵营，知道不少古老的故事，背景不简单。', 
    image: 'images/characters/naiful.png', 
    skills: ['水元素攻击', '水元素技能', '水元素防御'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'], 
    talent_materials: ['伏尼奇的教导', '伏尼奇的指引', '伏尼奇的哲学', '净水之心', '骗骗花蜜', '微光花蜜', '原素花蜜'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '奈芙尔是挪德卡莱伏尼奇商会阵营的重要人物，知道不少古老的故事，背景不简单。她以水元素之力进行战斗，展现出神秘而强大的力量。',
    constellations: ['伏尼奇商会', '水元素攻击', '水元素技能', '水元素防御', '水之智慧', '古老的秘密'],
    passive_talents: ['水元素亲和', '古老的智慧', '水之奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '菈乌玛': { 
    name: '菈乌玛', 
    element: '草元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '挪德卡莱', 
    description: '霜月之子部落的祭司角色，以草元素角色身份登场。', 
    image: 'images/characters/lawuma.png', 
    skills: ['草元素攻击', '草元素技能', '草元素防御'], 
    ascension_materials: ['生长碧翡碎屑', '生长碧翡断片', '生长碧翡块', '生长碧翡', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'], 
    talent_materials: ['霜月之子的教导', '霜月之子的指引', '霜月之子的哲学', '枯荣之实', '蕈兽孢子', '荧光孢粉', '孢囊晶尘'],
    base_hp: 1020,
    base_atk: 52,
    base_def: 34,
    character_story: '菈乌玛是挪德卡莱霜月之子部落的祭司角色，以草元素之力进行战斗。她作为部落的祭司，掌握着古老的草元素知识和神秘的力量。',
    constellations: ['霜月之子', '草元素攻击', '草元素技能', '草元素防御', '草之智慧', '古老的祭典'],
    passive_talents: ['草元素亲和', '古老的智慧', '草之奥秘'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  },
  '哥伦比娅': { 
    name: '哥伦比娅', 
    element: '水元素', 
    weapon: '法器', 
    rarity: 5, 
    region: '挪德卡莱', 
    description: '“月之少女”，剧情设定为新月神，可输出可辅助，是月反应体系核心。', 
    image: 'images/characters/gelunbiya.png', 
    skills: ['月露泼降', '万古潮汐', '她的乡愁'], 
    ascension_materials: ['涤净青金碎屑', '涤净青金断片', '涤净青金块', '涤净青金', '漫天的辉角', '史莱姆凝胶', '史莱姆清', '史莱姆原浆'], 
    talent_materials: ['月光的教导', '月光的指引', '月光的哲学', '贤者的假面', '史莱姆凝胶', '史莱姆清', '史莱姆原浆'],
    base_hp: 1050,
    base_atk: 50,
    base_def: 35,
    character_story: '哥伦比娅是“月之少女”，剧情设定为新月神，可输出可辅助，是月反应体系的核心角色。她拥有强大的水元素力量和独特的月感电反应能力。',
    constellations: ['新月神', '月露泼降', '万古潮汐', '她的乡愁', '月光的祝福', '潮汐的守护'],
    passive_talents: ['月光的祝福', '潮汐的守护', '月感电反应'],
    voice_actor_cn: '季冠霖',
    voice_actor_jp: '石见舞菜香'
  }
};

// 重新组织角色数据，按照指定字段顺序输出
function transformCharacterData() {
  const transformedData = [];
  
  for (const [key, value] of Object.entries(characters)) {
    const characterData = {
      // 基础信息
      NAME: value.name,
      element: value.element,
      weapon: value.weapon,
      rarity: value.rarity,
      region: value.region,
      description: value.description,
      image: value.image,
      
      // 技能信息
      normal_attack: value.skills[0],
      elemental_skill: value.skills[1],
      elemental_burst: value.skills[2],
      
      // 材料信息
      ascension_materials: value.ascension_materials,
      talent_materials: value.talent_materials,
      
      // 基础属性
      base_hp: value.base_hp || 0,
      base_atk: value.base_atk || 0,
      base_def: value.base_def || 0,
      
      // 角色故事
      character_story: value.character_story || '暂无故事',
      
      // 命之座
      constellations: value.constellations || [],
      
      // 被动天赋
      passive_talents: value.passive_talents || [],
      
      // 声优信息
      voice_actor_cn: value.voice_actor_cn || '未知',
      voice_actor_jp: value.voice_actor_jp || '未知',
    };
    
    transformedData.push(characterData);
  }
  
  return transformedData;
}

// 输出结果
const result = transformCharacterData();
console.log(JSON.stringify(result, null, 2));