-- Table: users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `users` (`id`, `username`, `email`, `password`) VALUES (1, 'Ease', '2119318733@qq.com', '$2b$10$SKbEn7JsQcONMFUT/E762ObuYxw4rjKhCIyZuCi7prEmef/EYOb0a');
INSERT INTO `users` (`id`, `username`, `email`, `password`) VALUES (3, '安逸QAQ', '14789509113@sina.com', '$2b$10$pcrtuP1rR2MiwwDYLZejrO5Z6aT6BjBcZYXkYMk9G5vWwISE1GCNS');

-- Table: characters
CREATE TABLE IF NOT EXISTS `characters` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `element` varchar(50) NOT NULL,
  `weapon` varchar(50) NOT NULL,
  `rarity` int NOT NULL,
  `region` varchar(50) NOT NULL,
  `description` text,
  `image` varchar(255) DEFAULT NULL,
  `normal_attack` varchar(255) DEFAULT NULL,
  `elemental_skill` varchar(255) DEFAULT NULL,
  `elemental_burst` varchar(255) DEFAULT NULL,
  `ascension_materials` text,
  `talent_materials` text,
  `base_hp` int NOT NULL,
  `base_atk` int NOT NULL,
  `base_def` int NOT NULL,
  `character_story` text,
  `constellations` text,
  `passive_talents` text,
  `voice_actor_cn` varchar(255) DEFAULT NULL,
  `voice_actor_jp` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=191 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (1, '阿贝多', '岩元素', '单手剑', 5, '蒙德', '西风骑士团的首席炼金术士，“黄金”莱茵多特的造物。', 'images/characters/abeiduo.png', '创生法·拟造阳华', '诞生式·大地之潮', '辉光·启明星', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","玄岩之塔","骗骗花蜜","微光花蜜","原素花蜜"]', '["自由的教导","自由的指引","自由的哲学","血玉之枝","骗骗花蜜","微光花蜜","原素花蜜"]', 1000, 52, 31, '阿贝多是西风骑士团的首席炼金术士，他的真实身份是“黄金”莱茵多特创造的人造人。他在雪山深处进行着神秘的研究，探索着世界的真相。', '["白垩之子","创生法·拟造阳华","诞生式·大地之潮","辉光·启明星","无瑕的纯白","黄金的血脉"]', '["天才的创造","白垩的子嗣","大地的馈赠"]', 'Mace', '野岛健儿');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (2, '芭芭拉', '水元素', '法器', 4, '蒙德', '西风教会的治愈者，擅长使用水元素治疗。', 'images/characters/barbara.png', '圣歌·抚慰', '圣歌·净化', '圣歌·祝福', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["自由的教导","自由的指引","自由的哲学","血玉之枝","骗骗花蜜","微光花蜜","原素花蜜"]', 950, 48, 29, '芭芭拉是西风教会的祈礼牧师，同时也是蒙德城的偶像歌手。她以清纯可爱的形象和治愈的歌声受到市民的喜爱，用她的水元素力量为人们带来希望和治愈。', '["光辉的季节","圣歌·抚慰","圣歌·净化","圣歌·祝福","偶像的魅力","奇迹的歌声"]', '["治愈的歌声","偶像的光环","水之祈愿"]', '宋媛媛', '鬼头明里');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (3, '迪卢克', '火元素', '双手剑', 5, '蒙德', '蒙德城的酒馆老板，火焰与黑暗的掌控者。', 'images/characters/diluc.png', '逆焰之刃', '冰潮的涡旋', '凝浪之光剑', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["抗争的教导","抗争的指引","抗争的哲学","血玉之枝","骗骗花蜜","微光花蜜","原素花蜜"]', 1050, 56, 33, '迪卢克是蒙德城最富有的家族——莱艮芬德家族的继承人。他曾是西风骑士团的骑兵队长，但因父亲的死而离开骑士团，成为了暗中守护蒙德的“暗夜英雄”。', '["炎之魔女","逆焰之刃","冰潮的涡旋","凝浪之光剑","火焰的意志","暗夜的守护"]', '["火焰的掌控","暗夜的步伐","正义的裁决"]', '马洋', '小野贤章');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (4, '刻晴', '雷元素', '单手剑', 5, '璃月', '璃月港的“玉衡”星，雷厉风行的领导者。', 'images/characters/keqing.png', '云来剑法', '星斗归位', '天街巡游', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷光棱镜","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 54, 32, '刻晴是璃月港的“玉衡”星，雷厉风行的领导者。她以凡人之躯比肩神明，坚信人类的命运应由自己掌握，积极推动璃月港的现代化发展。', '["雷厉","星斗归位","天街巡游","雷楔","雷罚","雷劫"]', '["玉衡之贵","星斗的指引","雷元素的亲和"]', '谢莹', '高桥李依');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (5, '温迪', '风元素', '弓', 5, '蒙德', '蒙德的吟游诗人，风神的化身。', 'images/characters/venti.png', '风之诗篇', '风之舞步', '风之咏叹', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["自由的教导","自由的指引","自由的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 980, 50, 30, '温迪是蒙德的吟游诗人，也是风神巴巴托斯的化身。他以轻松幽默的性格和美妙的歌声闻名，虽然看起来像个顽皮的孩子，但实际上拥有着深厚的智慧和强大的力量。', '["风之诗篇","风之舞步","风之咏叹","风神的祝福","自由之风","诗人的传说"]', '["风神的眷顾","风之诗篇","风之舞步"]', '李兰陵', '石川英郎');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (6, '钟离', '岩元素', '长柄武器', 5, '璃月', '往生堂的神秘客卿，真实身份是岩王帝君。', 'images/characters/zhongli.png', '岩雨', '地心', '天星', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1200, 48, 42, '钟离是璃月港的神秘客卿，真实身份是岩王帝君。他以温和睿智的形象深受民众喜爱，同时拥有着悠久的历史和强大的力量。他致力于保护璃月的和平与发展。', '["岩王帝君","岩雨","地心","天星","岩之守护","岩王的智慧"]', '["岩王的守护","岩之庇护","岩王的威严"]', '彭博', '中井和哉');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (7, '雷电将军', '雷元素', '长柄武器', 5, '稻妻', '稻妻的统治者，追求永恒的雷神。', 'images/characters/leidian.png', '神变·恶曜开眼', '神变·雷罚恶曜', '梦想真说', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷王的雷电","旧武器零件","破损的面具","污秽的面具"]', '["雷电的教导","雷电的指引","雷电的哲学","雷电将军的战利品","旧武器零件","破损的面具","污秽的面具"]', 1100, 58, 36, '雷电将军是稻妻的统治者，追求永恒的雷神。她以强大的雷电之力统治着稻妻，为了达成自己的目标不惜一切代价，是一位既强大又神秘的领袖人物。', '["雷神的威严","神变·恶曜开眼","神变·雷罚恶曜","梦想真说","雷神的意志","永恒的雷电"]', '["雷神的威严","雷电的统治","永恒的雷电"]', '菊花花', '石川由依');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (8, '纳西妲', '草元素', '法器', 5, '须弥', '须弥的神明，小吉祥草王。', 'images/characters/naxida.png', '普攻', '所闻遍计', '诸法空相', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["智慧的教导","智慧的指引","智慧的哲学","纳西妲的战利品","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 960, 46, 30, '纳西妲是须弥的神明，小吉祥草王。她以智慧和知识著称，是须弥教令院的象征性人物。她拥有丰富的知识和强大的草元素力量，是须弥智慧的化身。', '["小吉祥草王","所闻遍计","诸法空相","智慧之源","草神的眷顾","知识的传承"]', '["智慧的传承","草元素的亲和","知识的启示"]', '花铃', '茅野爱衣');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (9, '芙宁娜', '水元素', '单手剑', 5, '枫丹', '枫丹的水之神，掌管正义与审判。', 'images/characters/funingna.png', '普攻', '水之誓约', '裁决之潮', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","水之滴","净水之心","纯水之愿","浓缩树脂"]', '["正义的教导","正义的指引","正义的哲学","芙宁娜的战利品","净水之心","纯水之愿","浓缩树脂"]', 1020, 52, 34, '芙宁娜是枫丹的水之神，掌管正义与审判。她以水元素的力量维护着枫丹的秩序和正义，是一位强大而公正的神明。', '["水之神","水之誓约","裁决之潮","正义的化身","审判之水","水神的威严"]', '["正义的审判","水元素的亲和","审判之水"]', '钱琛', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (10, '魈', '风元素', '长柄武器', 5, '璃月', '璃月港的“护法夜叉”，守护璃月已有千年。', 'images/characters/xiao.png', '风轮两立', '靖妖傩舞', '降魔大圣', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","幼岩龙蜥的玉髓","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","风魔龙的 plume","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1080, 54, 35, '魈是璃月港的“护法夜叉”，守护璃月已有千年。他以风元素的力量保护着璃月的人民，是一个沉默寡言但内心善良的守护者。', '["护法夜叉","风轮两立","靖妖傩舞","降魔大圣","风神的眷顾","夜叉的守护"]', '["夜叉的守护","风元素的亲和","风神的祝福"]', '李兰陵', '杉田智和');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (11, '胡桃', '火元素', '长柄武器', 5, '璃月', '璃月港"往生堂"的堂主，性格活泼开朗。', 'images/characters/hutao.png', '魂引之仪', '蝶引来生', '安神秘法', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","燃愿玛瑙","骗骗花蜜","微光花蜜","原素花蜜"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","古岩龙蜥的 aerosiderite","骗骗花蜜","微光花蜜","原素花蜜"]', 1150, 58, 34, '胡桃是璃月港"往生堂"的堂主，性格活泼开朗。她以独特的魅力和精湛的医术在璃月港广受尊敬，虽然看似调皮，但其实非常关心他人。', '["往生堂的堂主","魂引之仪","蝶引来生","安神秘法","生命的延续","冥界的使者"]', '["生命的守护","冥界的祝福","往生堂的传承"]', '赵爽', '小松未可子');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (12, '甘雨', '冰元素', '弓', 5, '璃月', '“七星”的秘书，半人半仙的存在，工作认真负责。', 'images/characters/ganyu.png', '流天射术', '山泽麟迹', '降众天华', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1080, 52, 35, '甘雨是璃月港“七星”的秘书，半人半仙的存在。她以优雅的气质和卓越的能力在璃月港工作，是璃月的守护者之一。', '["七星的秘书","流天射术","山泽麟迹","降众天华","天华的守护","星辰的祝福"]', '["天华的守护","星辰的庇护","天华的智慧"]', '林簌', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (13, '枫原万叶', '风元素', '单手剑', 5, '稻妻', '稻妻的浪人武士，曾是枫原家的少爷。', 'images/characters/fengyuan.png', '万叶之一刀', '千早振', '风物之诗咏', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["雷电的教导","雷电的指引","雷电的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 54, 32, '枫原万叶是稻妻的浪人武士，曾是枫原家的少爷。他以潇洒的剑术和对自然的深刻理解而闻名，是稻妻的传奇人物。', '["万叶之歌","万叶之一刀","千早振","风物之诗咏","风之诗篇","叶的传说"]', '["风之诗篇","叶的传承","风的祝福"]', '李兰陵', '杉田智和');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (14, '宵宫', '火元素', '弓', 5, '稻妻', '长野原家的女儿，擅长制作烟花。', 'images/characters/xiaogong.png', '弓术·炎律', '焰硝庭火舞', '琉金云间草', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["雷电的教导","雷电的指引","雷电的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1000, 52, 30, '宵宫是稻妻长野原家的女儿，擅长制作烟花。她以独特的烟花制作工艺和热情的性格而闻名，是稻妻的代表性角色之一。', '["烟花少女","弓术·炎律","焰硝庭火舞","琉金云间草","火之热情","烟花绽放"]', '["火之热情","烟花的祝福","火焰的亲和"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (15, '神里绫华', '冰元素', '单手剑', 5, '稻妻', '稻妻神里家的大小姐，优雅的剑士。', 'images/characters/shenli.png', '神里流·霜灭', '神里流·霜灭', '神里流·霜灭', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","冰之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["雷电的教导","雷电的指引","雷电的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '神里绫华是稻妻神里家的大小姐，以优雅的剑术和高贵的气质而闻名。她精通神里流剑术，是稻妻的代表性角色之一。', '["神里流","神里流·霜灭","神里流·冰舞","神里流·雪华","冰元素亲和","神里家的骄傲"]', '["冰元素亲和","神里流剑术","雪华的祝福"]', '小N', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (16, '神里绫人', '水元素', '单手剑', 5, '稻妻', '稻妻神里家的家主，心思缜密。', 'images/characters/shenli_ren.png', '神里流·镜花', '神里流·水囿', '神里流·霰步', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["雷电的教导","雷电的指引","雷电的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '神里绫人是稻妻神里家的家主，以深思熟虑的性格和高超的剑术而闻名。他是稻妻的重要人物之一。', '["神里流","神里流·镜花","神里流·水囿","神里流·霰步","水元素亲和","神里家的智慧"]', '["水元素亲和","神里流剑术","水之庇护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (17, '夜兰', '水元素', '弓', 5, '璃月', '璃月港的情报人员，身份神秘。', 'images/characters/yelan.png', '破局矢', '渊图玲珑骰', '天网恢恢', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '夜兰是璃月港的情报人员，身份神秘。她以敏锐的洞察力和高超的情报收集能力闻名，是璃月港重要的情报来源。', '["情报专家","破局矢","渊图玲珑骰","天网恢恢","水元素亲和","神秘的守护"]', '["水元素亲和","情报收集","神秘的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (18, '达达利亚', '水元素', '弓', 5, '璃月', '执行官"公子"，擅长水元素战斗。', 'images/characters/dadaliya.png', '深渊之息', '海渊之怒', '深海之誓', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["正义的教导","正义的指引","正义的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '达达利亚是愚人众执行官"公子"，以水元素之力进行战斗。他性格复杂，既是敌人也是朋友，是枫丹的重要角色。', '["深渊的守护者","深渊之息","海渊之怒","深海之誓","水元素亲和","深渊的意志"]', '["水元素亲和","深渊的祝福","深海的守护"]', '李胤春', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (19, '优菈', '冰元素', '双手剑', 5, '蒙德', '劳伦斯家族的末裔，西风骑士团的游击队长。', 'images/characters/youla.png', '逆焰之刃', '冰潮的涡旋', '凝浪之光剑', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["抗争的教导","抗争的指引","抗争的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1080, 54, 35, '优菈是劳伦斯家族的末裔，西风骑士团的游击队长。她以冰元素之力进行战斗，性格坚强且富有责任感。', '["冰之女王","逆焰之刃","冰潮的涡旋","凝浪之光剑","冰元素亲和","骑士的荣耀"]', '["冰元素亲和","冰之守护","骑士的荣耀"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (20, '申鹤', '冰元素', '长柄武器', 5, '璃月', '璃月港的修行者，是留云借风真君的弟子。', 'images/characters/shenhe.png', '仪典剑术', '仰灵威·遣灵真诀', '神女遣灵真诀', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1080, 52, 35, '申鹤是璃月港的修行者，是留云借风真君的弟子。她以冰元素之力进行战斗，性格冷静而坚定，拥有着强大的实力。', '["神女的传承","仪典剑术","仰灵威·遣灵真诀","神女遣灵真诀","冰元素亲和","神女的守护"]', '["冰元素亲和","神女的祝福","冰之守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (21, '八重神子', '雷元素', '法器', 5, '稻妻', '稻妻鸣神大社的宫司，雷电影的好友。', 'images/characters/bachong.png', '千早振', '天狐神火', '神樱大祓', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷王的雷电","旧武器零件","破损的面具","污秽的面具"]', '["雷电的教导","雷电的指引","雷电的哲学","雷电将军的战利品","旧武器零件","破损的面具","污秽的面具"]', 1020, 52, 34, '八重神子是稻妻鸣神大社的宫司，也是雷电将军的好友。她以雷元素之力进行战斗，拥有强大的雷电力量和神秘的神力。', '["神子的智慧","千早振","天狐神火","神樱大祓","雷元素亲和","神社的守护"]', '["雷元素亲和","神子的祝福","雷电的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (22, '可莉', '火元素', '法器', 5, '蒙德', '魔女爱丽丝的女儿，喜欢炸鱼。', 'images/characters/klee.png', '炸弹爆炸', '烈焰冲锋', '爆炸狂欢', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["自由的教导","自由的指引","自由的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 1000, 52, 30, '可莉是魔女爱丽丝的女儿，以爆炸魔法著称。她天真烂漫，喜欢用炸弹制造惊喜，是提瓦特世界中最受欢迎的角色之一。', '["爆炸专家","炸弹爆炸","烈焰冲锋","爆炸狂欢","火元素亲和","魔法的喜悦"]', '["火元素亲和","爆炸的喜悦","魔法的祝福"]', '花铃', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (23, '七七', '冰元素', '单手剑', 5, '璃月', '被仙人复活的僵尸少女，记忆力不好。', 'images/characters/qiqi.png', '普攻', '冰寒过隙', '寒病鬼差', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1080, 52, 35, '七七是被仙人复活的僵尸少女，记忆力不好。她以冰元素之力进行战斗，拥有强大的治疗能力和冰霜力量。', '["僵尸少女","冰寒过隙","寒病鬼差","冰元素亲和","生命之源","治疗的祝福"]', '["冰元素亲和","生命之源","治疗的祝福"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (24, '莫娜', '水元素', '法器', 5, '蒙德', '蒙德的占星术士，擅长使用水元素占卜。', 'images/characters/mona.png', '星象占卜', '水之预言', '命运之轮', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["自由的教导","自由的指引","自由的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '莫娜是蒙德的占星术士，以水元素之力进行占卜。她以精准的预言和神秘的气质著称，是蒙德的智慧象征。', '["占星术","星象占卜","水之预言","命运之轮","水元素亲和","预言的奥秘"]', '["水元素亲和","预言的智慧","命运的指引"]', '季冠霖', '小原好美');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (25, '丽莎', '雷元素', '法器', 4, '蒙德', '西风教会的学者，擅长使用雷元素魔法。', 'images/characters/lisa.png', '雷电咒语', '雷击术', '雷电风暴', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["自由的教导","自由的指引","自由的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 900, 42, 26, '丽莎是西风教会的学者，同时也是蒙德图书馆的管理员。她以渊博的知识和强大的雷元素魔法著称，看似慵懒却隐藏着高深的实力。', '["雷之眷顾","雷电咒语","雷击术","雷电风暴","雷元素亲和","智慧的传承"]', '["雷元素亲和","智慧的启迪","魔法的精通"]', '季冠霖', '田中理恵');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (26, '凯亚', '冰元素', '单手剑', 4, '蒙德', '西风骑士团的骑兵队长，擅长使用冰元素。', 'images/characters/kaeya.png', '冰霜斩击', '冰冻之刃', '寒冰领域', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","冰之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["自由的教导","自由的指引","自由的哲学","冰之心","骗骗花蜜","微光花蜜","原素花蜜"]', 900, 42, 26, '凯亚是西风骑士团的骑兵队长，以冰元素之力进行战斗。他性格风趣幽默，总是带着一丝神秘感，是蒙德的重要角色之一。', '["冰之剑","冰霜斩击","冰冻之刃","寒冰领域","冰元素亲和","骑士的荣耀"]', '["冰元素亲和","骑士的直觉","冰之优雅"]', '孙晔', '鸟海浩辅');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (27, '安柏', '火元素', '弓', 4, '蒙德', '西风骑士团的侦查骑士，擅长使用火元素弓箭。', 'images/characters/amber.png', '火焰箭', '烈焰射击', '燃烧之箭', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["自由的教导","自由的指引","自由的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 900, 40, 25, '安柏是西风骑士团的侦查骑士，以热情洋溢的性格和精湛的箭术著称。她是蒙德的活跃分子，热爱滑翔和冒险，总是充满活力地完成任务。', '["火之射手","火焰箭","烈焰射击","燃烧之箭","火元素亲和","侦查骑士的荣耀"]', '["火元素亲和","侦查的直觉","滑翔的技巧"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (28, '琴', '风元素', '单手剑', 5, '蒙德', '西风骑士团的代理团长，风元素的掌控者。', 'images/characters/jean.png', '风之剑技', '风之庇护', '风之守护', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["自由的教导","自由的指引","自由的哲学","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '琴是西风骑士团的代理团长，以风元素之力守护蒙德。她正直严谨，是骑士团的中流砥柱，深受团员们的尊敬和信赖。', '["风之守护","风之剑技","风之庇护","风之守护","风元素亲和","骑士团的荣耀"]', '["风元素亲和","骑士团的守护","风之治愈"]', '林簌', '田村由香里');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (29, '罗莎莉亚', '冰元素', '长柄武器', 4, '蒙德', '西风骑士团的修女，行事风格独特。', 'images/characters/luoshalia.png', '噬罪的告解', '穿刺之冰', '终末的圣礼', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["抗争的教导","抗争的指引","抗争的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '罗莎莉亚是西风骑士团的修女，以冰元素之力进行战斗。她行事风格独特，看似冷漠却内心善良，是蒙德的神秘守护者。', '["噬罪的告解","穿刺之冰","终末的圣礼","冰元素亲和","修女的秘密","黑暗的守护"]', '["冰元素亲和","修女的直觉","黑暗的祝福"]', '张安琪', '加隈亚衣');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (30, '砂糖', '风元素', '法器', 4, '蒙德', '阿贝多的弟子，擅长使用风元素。', 'images/characters/sugar.png', '草元素研究', '植物实验', '药剂调配', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["智慧的教导","智慧的指引","智慧的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 920, 44, 28, '砂糖是阿贝多的助手，痴迷于炼金术研究。她擅长利用风元素进行实验，希望通过炼金术让世界变得更美好。', '["风之炼金","草元素研究","植物实验","药剂调配","风元素亲和","炼金的奥秘"]', '["风元素亲和","炼金的直觉","实验的精准"]', '谢莹', '藤田咲');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (31, '班尼特', '火元素', '单手剑', 4, '蒙德', '班尼冒险团的团长，倒霉蛋。', 'images/characters/bennett.png', '火焰鼓舞', '火焰护盾', '火焰爆发', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["自由的教导","自由的指引","自由的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 900, 42, 26, '班尼特是班尼冒险团的团长，以不幸的运气和热情的性格著称。尽管总是遇到倒霉事，但他从不放弃冒险的精神，是蒙德最乐观的冒险家之一。', '["幸运之火","火焰鼓舞","火焰护盾","火焰爆发","火元素亲和","冒险的意志"]', '["火元素亲和","冒险的热情","幸运的祝福"]', '穆雪婷', '逢坂良太');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (32, '菲谢尔', '雷元素', '弓', 4, '蒙德', '来自幽夜净土的菲谢尔，擅长使用雷元素。', 'images/characters/fischl.png', '雷电箭', '雷电陷阱', '雷电审判', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["正义的教导","正义的指引","正义的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '菲谢尔是来自幽夜净土的断罪之皇女，与名为奥兹的夜鸦为伴。她以雷元素之力和神秘的气质著称，是枫丹的传奇人物之一。', '["断罪之皇女","雷电箭","雷电陷阱","雷电审判","雷元素亲和","幽夜的守护"]', '["雷元素亲和","幽夜的智慧","奥兹的陪伴"]', 'Mace', '内田真礼');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (33, '诺艾尔', '岩元素', '双手剑', 4, '蒙德', '还未成为骑士的女仆，擅长使用岩元素防御。', 'images/characters/noelle.png', '岩石护盾', '岩石打击', '岩石屏障', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["自由的教导","自由的指引","自由的哲学","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 940, 45, 29, '诺艾尔是蒙德的女仆，梦想成为西风骑士团的一员。她以岩元素之力进行防御，性格温柔且充满责任感，总是尽心尽力地帮助他人。', '["女仆的决心","岩石护盾","岩石打击","岩石屏障","岩元素亲和","骑士的梦想"]', '["岩元素亲和","女仆的细心","防御的守护"]', '宴宁', '高尾奏音');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (34, '雷泽', '雷元素', '双手剑', 4, '蒙德', '与狼群一起长大的孩子，擅长使用雷元素攻击。', 'images/characters/razor.png', '雷电撕裂', '雷电冲击', '雷电风暴', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["自由的教导","自由的指引","自由的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '雷泽是与狼群一起长大的孩子，以雷元素之力进行战斗。他虽然不擅长人类的语言，但拥有敏锐的直觉和强大的战斗力，是蒙德的野性守护者。', '["狼之末裔","雷电撕裂","雷电冲击","雷电风暴","雷元素亲和","狼的守护"]', '["雷元素亲和","狼的直觉","战斗的本能"]', '秦且歌', '内山昂辉');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (35, '香菱', '火元素', '长柄武器', 4, '璃月', '璃月港的厨师，总是充满活力，擅长制作各种美食。', 'images/characters/xiangling.png', '白案功夫', '锅巴出击', '旋火轮', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 920, 44, 28, '香菱是璃月港万民堂的厨师，以热情洋溢的性格和精湛的厨艺著称。她擅长将烹饪技巧融入战斗，是璃月最受欢迎的厨师之一。', '["烈火佳肴","白案功夫","锅巴出击","旋火轮","火元素亲和","厨艺的巅峰"]', '["火元素亲和","烹饪的灵感","美食的祝福"]', '小N', '小泽亚李');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (36, '行秋', '水元素', '单手剑', 4, '璃月', '璃月港飞云商会的二少爷，喜欢阅读武侠小说。', 'images/characters/xingqiu.png', '古华剑法', '画雨笼山', '裁雨留虹', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 920, 44, 28, '行秋是璃月港飞云商会的二少爷，热爱阅读武侠小说，常将书中招式融入自己的剑法。他以水元素之力战斗，展现出优雅灵动的剑技，是璃月港年轻一代中的佼佼者。', '["万叶飘零","古华剑法","画雨笼山","裁雨留虹","水元素亲和","武侠的传承"]', '["水元素亲和","剑法精通","小说灵感"]', '斑马', '市来光弘');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (37, '重云', '冰元素', '双手剑', 4, '璃月', '璃月港的驱邪方士，体内蕴含着纯阳之体。', 'images/characters/chongyun.png', '云来剑法', '重华叠霜', '云开星落', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '重云是璃月港的驱邪方士，体内蕴含着纯阳之体。他以冰元素之力进行战斗，擅长使用双手剑，是璃月的重要角色之一。', '["纯阳之体","云来剑法","重华叠霜","云开星落","冰元素亲和","驱邪的意志"]', '["冰元素亲和","纯阳的守护","驱邪的祝福"]', 'kinsen', '下野紘');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (38, '凝光', '岩元素', '法器', 4, '璃月', '璃月港的“天权”星，掌握着璃月的经济命脉。', 'images/characters/ningguang.png', '星陨剑', '璇玑屏', '天权崩玉', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '凝光是璃月港的“天权”星，掌握着璃月的经济命脉。她以岩元素之力进行战斗，展现出强大的财富掌控能力和战斗技巧。', '["天权","星陨剑","璇玑屏","天权崩玉","岩元素亲和","财富的守护"]', '["岩元素亲和","财富的守护","经济的智慧"]', '杜冥鸦', '大原沙耶香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (39, '北斗', '雷元素', '双手剑', 4, '璃月', '璃月港“南十字”船队的船长，性格豪爽。', 'images/characters/beidou.png', '征涛快斩', '捉浪', '斫雷', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '北斗是璃月港“南十字”船队的船长，以豪爽的性格和强大的实力著称。她曾单枪匹马挑战海怪，赢得了“南十字”的称号，是璃月港的传奇人物。', '["南十字","征涛快斩","捉浪","斫雷","雷元素亲和","船队的荣耀"]', '["雷元素亲和","船队的庇护","风暴的掌控"]', '唐雅菁', '斎藤千和');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (40, '辛焱', '火元素', '双手剑', 4, '璃月', '璃月港的摇滚歌手，擅长使用火元素。', 'images/characters/xinyan.png', '摇滚的律动', '热情拂扫', '演出开始', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 920, 44, 28, '辛焱是璃月港的摇滚歌手，以火元素之力进行表演和战斗。她以独特的摇滚风格和热情的性格著称，是璃月港的音乐象征。', '["摇滚之心","摇滚的律动","热情拂扫","演出开始","火元素亲和","音乐的力量"]', '["火元素亲和","音乐的热情","摇滚的力量"]', '王雅欣', '高桥智秋');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (41, '烟绯', '火元素', '法器', 4, '璃月', '璃月港的律法咨询师，半仙之体。', 'images/characters/yanfei.png', '丹火印', '丹火印·点', '业火荧煌', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 920, 44, 28, '烟绯是璃月港的律法咨询师，半仙之体。她以火元素之力维护着璃月的法律秩序，同时也是一位热情洋溢的少女。', '["法之守护","丹火印","丹火印·点","业火荧煌","火元素亲和","律法的智慧"]', '["火元素亲和","律法的智慧","半仙之体"]', '谢莹', '高桥李依');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (42, '五郎', '岩元素', '弓', 4, '稻妻', '海祇岛的大将，擅长使用岩元素。', 'images/characters/gorou.png', '岩之守卫', '岩之屏障', '岩之突袭', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["雷电的教导","雷电的指引","雷电的哲学","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '五郎是海祇岛的大将，以岩元素之力进行战斗。他以忠诚和勇敢著称，是海祇岛的重要守护者。', '["岩之守卫","岩之屏障","岩之突袭","岩元素亲和","大将的荣耀","忠诚的守护"]', '["岩元素亲和","大将的荣耀","忠诚的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (43, '九条裟罗', '雷元素', '弓', 4, '稻妻', '稻妻天领奉行的大将，忠于雷电将军。', 'images/characters/jiutiao.png', '鸦羽弓术', '煌煌千道镇式', '天狗食月', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["雷电的教导","雷电的指引","雷电的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '九条裟罗是稻妻天领奉行的大将，忠于雷电将军。她以雷元素之力进行战斗，拥有强大的雷电力量和忠诚的性格。', '["雷之守护","鸦羽弓术","煌煌千道镇式","天狗食月","雷元素亲和","忠诚的守护"]', '["雷元素亲和","忠诚的守护","雷电的力量"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (44, '荒泷一斗', '岩元素', '双手剑', 5, '稻妻', '稻妻“荒泷派”的头领，性格豪放。', 'images/characters/huanglong.png', '乱神之怪力', '魔像·怒目', '荒泷乱舞', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["雷电的教导","雷电的指引","雷电的哲学","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '荒泷一斗是稻妻荒泷派的头领，以岩元素之力进行战斗。他性格豪放不羁，是稻妻的传奇人物之一。', '["荒泷派","乱神之怪力","魔像·怒目","荒泷乱舞","岩元素亲和","豪放的意志"]', '["岩元素亲和","豪放的意志","荒泷派的荣耀"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (45, '云堇', '岩元素', '长柄武器', 4, '璃月', '璃月港的戏曲演员，擅长唱念做打。', 'images/characters/yunjin.png', '云翰剑法', '破嶂见旌仪', '旋云开相', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '云堇是璃月港著名的戏曲演员，以精湛的唱念做打技艺闻名。她将传统戏曲与岩元素力量相结合，创造出独特的战斗风格。', '["戏韵流芳","云翰剑法","破嶂见旌仪","旋云开相","岩元素亲和","戏曲的传承"]', '["岩元素亲和","戏曲的韵律","舞台的掌控"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (46, '鹿野院平藏', '风元素', '法器', 4, '稻妻', '稻妻天领奉行的侦探，聪明机智。', 'images/characters/luye.png', '心朝乂安', '装卦·明察', '秘策·穷理', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["雷电的教导","雷电的指引","雷电的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '鹿野院平藏是稻妻天领奉行的侦探，以风元素之力进行推理和战斗。他聪明机智，擅长破解各种疑难案件。', '["侦探的智慧","心朝乂安","装卦·明察","秘策·穷理","风元素亲和","推理的奥秘"]', '["风元素亲和","侦探的直觉","推理的智慧"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (47, '久岐忍', '雷元素', '单手剑', 4, '稻妻', '稻妻“荒泷派”的二把手，冷静理智。', 'images/characters/jiuqi.png', '阿波卡利斯的裁决', '护法之誓', '净土裁断', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["雷电的教导","雷电的指引","雷电的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '久岐忍是稻妻“荒泷派”的二把手，以雷元素之力进行战斗。她冷静理智，是荒泷派的重要支柱。', '["荒泷派二把手","阿波卡利斯的裁决","护法之誓","净土裁断","雷元素亲和","理智的守护"]', '["雷元素亲和","理智的守护","荒泷派的荣耀"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (48, '柯莱', '草元素', '弓', 4, '须弥', '须弥教令院的学徒，曾是蒙德的孤儿。', 'images/characters/keli.png', '蓄力箭', '苑田瞬发', '约定的花海', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["智慧的教导","智慧的指引","智慧的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 920, 44, 28, '柯莱是须弥教令院的学徒，曾是蒙德的孤儿。她以草元素之力进行战斗，拥有强大的草元素力量和坚韧的意志。', '["草之学徒","蓄力箭","苑田瞬发","约定的花海","草元素亲和","学徒的成长"]', '["草元素亲和","学徒的成长","草之守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (49, '多莉', '雷元素', '双手剑', 4, '须弥', '须弥的商人，经营着各种奇特商品。', 'images/characters/duoli.png', '金流弹反', '神奇的灯中幽精', '一千零一夜', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["智慧的教导","智慧的指引","智慧的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '多莉是须弥著名的商人，以经营各种奇特商品而闻名。她以雷元素之力进行战斗，拥有强大的雷电力量和敏锐的商业头脑。', '["商人的智慧","金流弹反","神奇的灯中幽精","一千零一夜","雷元素亲和","商业的奥秘"]', '["雷元素亲和","商业的智慧","财富的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (50, '提纳里', '草元素', '弓', 5, '须弥', '须弥教令院的学者，擅长植物学。', 'images/characters/tainali.png', '藏弓·序章', '识藏之花', '造生之种', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["智慧的教导","智慧的指引","智慧的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 1020, 52, 34, '提纳里是须弥教令院的学者，擅长植物学。他以草元素之力进行战斗，拥有丰富的植物学知识和强大的草元素力量。', '["植物学家","藏弓·序章","识藏之花","造生之种","草元素亲和","植物的奥秘"]', '["草元素亲和","植物的知识","草之守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (51, '赛诺', '雷元素', '长柄武器', 5, '须弥', '须弥教令院的大风纪官，公正严明。', 'images/characters/saino.png', '秘仪·律渊渡魂', '秘仪·迷踪之砂', '秘仪·真数谶言', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["智慧的教导","智慧的指引","智慧的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '赛诺是须弥教令院的大风纪官，以雷元素之力维护教令院的秩序。他公正严明，是须弥智慧的守护者之一。', '["大风纪官","秘仪·律渊渡魂","秘仪·迷踪之砂","秘仪·真数谶言","雷元素亲和","公正的裁决"]', '["雷元素亲和","公正的裁决","智慧的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (52, '妮露', '水元素', '单手剑', 5, '须弥', '须弥大巴扎的舞者，擅长水元素舞蹈。', 'images/characters/nilu.png', '普攻', '水环', '翩转惊鸿', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["智慧的教导","智慧的指引","智慧的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '妮露是须弥大巴扎的舞者，以水元素舞蹈著称。她的舞蹈优美动人，是须弥的文化象征之一。', '["水之舞者","水环","翩转惊鸿","水元素亲和","舞蹈的奥秘","水之祝福"]', '["水元素亲和","舞蹈的奥秘","水之祝福"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (53, '坎蒂丝', '水元素', '长柄武器', 4, '须弥', '须弥阿弥村的守护者，擅长使用水元素。', 'images/characters/candace.png', '水之契约', '水之谈判', '水之调和', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["正义的教导","正义的指引","正义的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 920, 44, 28, '坎蒂丝是须弥阿弥村的守护者，以水元素之力守护着村庄的和平。她拥有强大的水元素力量和坚定的意志，是阿弥村的重要支柱。', '["水之守护","水之契约","水之谈判","水之调和","水元素亲和","守护者的荣耀"]', '["水元素亲和","守护者的荣耀","水之祝福"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (54, '迪希雅', '火元素', '双手剑', 5, '须弥', '须弥的佣兵，性格豪爽。', 'images/characters/dixiya.png', '普攻', '炎之舞', '烈焰焚天', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["智慧的教导","智慧的指引","智慧的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '迪希雅是须弥的佣兵，性格豪爽。她以火元素之力进行战斗，拥有强大的战斗力和坚定的意志。', '["佣兵的荣耀","炎之舞","烈焰焚天","火元素亲和","战斗的意志","豪爽的性格"]', '["火元素亲和","战斗的意志","豪爽的性格"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (55, '流浪者', '风元素', '法器', 5, '须弥', '原愚人众执行官第六席“散兵”，现为流浪者。', 'images/characters/sanbing.png', '普攻', '空居·虚铃', '正机之神', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["雷电的教导","雷电的指引","雷电的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '流浪者是原愚人众执行官第六席“散兵”，现为流浪者。他以风元素之力进行战斗，拥有强大的风元素力量和神秘的身世背景。', '["流浪者","空居·虚铃","正机之神","风元素亲和","自由之风","流浪者的意志"]', '["风元素亲和","自由之风","流浪者的意志"]', 'kinsen', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (56, '珐露珊', '风元素', '弓', 4, '须弥', '200年前须弥教令院的学者，擅长风元素。', 'images/characters/falushan.png', '普攻', '风涡弹', '风息激荡', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["智慧的教导","智慧的指引","智慧的哲学","血玉之枝","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '珐露珊是200年前须弥教令院的学者，以风元素之力进行战斗。她拥有渊博的知识和强大的风元素力量，是须弥的智慧象征。', '["风之学者","风涡弹","风息激荡","风元素亲和","智慧的传承","风之奥秘"]', '["风元素亲和","智慧的传承","风之奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (57, '艾尔海森', '草元素', '单手剑', 5, '须弥', '须弥教令院的学者，冷静理智。', 'images/characters/aierhaisen.png', '普攻', '识藏之花', '造生之种', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["智慧的教导","智慧的指引","智慧的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 1020, 52, 34, '艾尔海森是须弥教令院的学者，以草元素之力进行战斗。他冷静理智，是须弥智慧的象征。', '["草之学者","识藏之花","造生之种","草元素亲和","智慧的传承","草之奥秘"]', '["草元素亲和","智慧的传承","草之奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (58, '卡维', '草元素', '法器', 4, '须弥', '须弥教令院的建筑师，性格温和。', 'images/characters/kayi.png', '普攻', '识藏之花', '造生之种', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["智慧的教导","智慧的指引","智慧的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 1020, 52, 34, '卡维是须弥教令院的建筑师，以草元素之力进行创作。他性格温和，擅长设计各种建筑，是须弥教令院的重要成员。', '["草之建筑师","识藏之花","造生之种","草元素亲和","建筑的智慧","设计的奥秘"]', '["草元素亲和","建筑的智慧","设计的灵感"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (59, '白术', '草元素', '法器', 5, '璃月', '璃月港“不卜庐”的老板，医术高明。', 'images/characters/baizhu.png', '行针步引', '愈气全形', '灵草愈疗', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 1080, 52, 35, '白术是璃月港“不卜庐”的老板，医术高明。他性格温和，擅长使用草元素进行治疗，是璃月港的重要医疗力量。', '["不卜庐的老板","行针步引","愈气全形","灵草愈疗","草元素亲和","医术的传承"]', '["草元素亲和","医术的传承","生命的守护"]', '秦且歌', '关智一');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (60, '瑶瑶', '草元素', '长柄武器', 4, '璃月', '萍姥姥最小的弟子，擅长使用草元素治疗。', 'images/characters/yaoyao.png', '草药调配', '治疗之术', '生命之源', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["智慧的教导","智慧的指引","智慧的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 960, 46, 30, '瑶瑶是璃月的药师，擅长使用草元素进行治疗。她是萍姥姥最小的弟子，继承了师父的医术精髓。', '["草之守护","草药调配","治疗之术","生命之源","草元素亲和","医者仁心"]', '["草元素亲和","治疗之术","生命之源"]', '季冠霖', '茅野爱衣');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (61, '米卡', '冰元素', '弓', 4, '蒙德', '须弥的侦察兵，擅长冰元素。', 'images/characters/mika.png', '普攻', '冰之箭', '冰雾花之舞', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["智慧的教导","智慧的指引","智慧的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '米卡是须弥的侦察兵，擅长使用冰元素进行侦察和战斗。她以敏捷的身手和精准的箭术著称。', '["冰之侦察","冰之箭","冰雾花之舞","冰元素亲和","寒风之影","雪地追踪"]', '["冰元素亲和","冰之敏捷","雪地追踪"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (62, '琳妮特', '风元素', '单手剑', 4, '枫丹', '枫丹的魔术师助手，擅长风元素。', 'images/characters/linniete.png', '普攻', '风之舞', '风息激荡', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["正义的教导","正义的指引","正义的哲学","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '琳妮特是枫丹著名魔术师林尼的助手，以优雅的风元素技巧和神秘的气质著称。她总是默默支持着林尼的表演，是魔术师组合中不可或缺的一部分。', '["风之幻影","风之舞","风息激荡","风元素亲和","魔术的奥秘","助手的守护"]', '["风元素亲和","魔术的敏捷","助手的专注"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (63, '林尼', '火元素', '弓', 5, '枫丹', '枫丹的魔术师，擅长火元素魔法。', 'images/characters/linni.png', '普攻', '火焰魔术', '烈焰表演', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["正义的教导","正义的指引","正义的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '林尼是枫丹著名的魔术师，以火元素之力进行表演和战斗。他与妹妹琳妮特一起，以精彩的魔术表演闻名枫丹，是枫丹舞台上的焦点人物。', '["魔术大师","火焰魔术","烈焰表演","火元素亲和","舞台的焦点","魔术的奥秘"]', '["火元素亲和","魔术的灵巧","舞台的掌控"]', 'kinsen', '下野紘');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (64, '菲米尼', '冰元素', '双手剑', 4, '枫丹', '枫丹的潜水员，擅长冰元素。', 'images/characters/feimini.png', '普攻', '冰之舞', '冰雾花之舞', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["正义的教导","正义的指引","正义的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 920, 44, 28, '菲米尼是枫丹的潜水员，以冰元素之力进行潜水和战斗。他擅长在水下探索和战斗，是枫丹水下探索的专家。', '["冰之潜水","冰之舞","冰雾花之舞","冰元素亲和","水下探索","潜水专家"]', '["冰元素亲和","水下探索","潜水专家"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (65, '夏洛蒂', '冰元素', '法器', 4, '枫丹', '枫丹的记者，以水元素之力记录真相。', 'images/characters/xialuodi.png', '笔锋流转', '真相探寻', '头条新闻', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["正义的教导","正义的指引","正义的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 920, 44, 28, '夏洛蒂是枫丹的记者，以水元素之力记录真相。她以敏锐的洞察力和公正的报道著称，是枫丹的真相守护者。', '["真相探寻","笔锋流转","头条新闻","水元素亲和","记者的直觉","真相的守护"]', '["水元素亲和","记者的直觉","真相的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (66, '娜维娅', '岩元素', '双手剑', 5, '枫丹', '枫丹的大小姐，执掌刺玫会。', 'images/characters/navia.png', '蔷薇剑舞', '蔷薇的誓言', '玫瑰之雨', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["正义的教导","正义的指引","正义的哲学","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '娜维娅是枫丹的大小姐，执掌刺玫会。她以岩元素之力守护枫丹的秩序，性格优雅且充满责任感，是枫丹的重要守护者。', '["蔷薇剑舞","蔷薇的誓言","玫瑰之雨","岩元素亲和","刺玫会的荣耀","优雅的守护"]', '["岩元素亲和","刺玫会的守护","优雅的意志"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (67, '夏沃蕾', '火元素', '弓', 4, '枫丹', '枫丹的检察官，擅长使用草元素。', 'images/characters/xiawolai.png', '草元素侦查', '草元素追踪', '草元素分析', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["正义的教导","正义的指引","正义的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 920, 44, 28, '夏沃蕾是枫丹的检察官，以草元素之力维护正义。她严谨公正，是枫丹法律体系的重要支柱。', '["草元素侦查","草元素追踪","草元素分析","草元素亲和","检察官的智慧","正义的守护"]', '["草元素亲和","检察官的直觉","正义的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (68, '千织', '岩元素', '单手剑', 5, '枫丹', '枫丹的服装设计师，擅长使用岩元素。', 'images/characters/qianzhi.png', '岩之编织', '岩之设计', '岩之创意', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["正义的教导","正义的指引","正义的哲学","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '千织是枫丹著名的服装设计师，以岩元素之力进行创作。她将岩石的坚韧与服装的柔美完美结合，创造出独特的时尚风格。', '["岩之编织","岩之设计","岩之创意","岩元素亲和","时尚的灵感","设计的奥秘"]', '["岩元素亲和","时尚的灵感","设计的奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (69, '克洛琳德', '雷元素', '单手剑', 5, '枫丹', '枫丹的审判官，以雷元素之力执行正义。', 'images/characters/keluolinde.png', '雷鸣回响', 'Shamshir的裁决', '誓约之眼', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["正义的教导","正义的指引","正义的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '克洛琳德是枫丹的审判官，以雷元素之力执行正义。她以公正严明的审判和强大的雷电力量著称，是枫丹法律体系的重要支柱。', '["雷之审判","雷鸣回响","Shamshir的裁决","誓约之眼","雷元素亲和","正义的守护"]', '["雷元素亲和","正义的守护","审判的智慧"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (70, '希格雯', '水元素', '弓箭', 5, '枫丹', '枫丹的医疗官，擅长使用水元素治疗。', 'images/characters/xigewen.png', '水之治疗', '水之复苏', '水之再生', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["正义的教导","正义的指引","正义的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '希格雯是枫丹的医疗官，以水元素之力进行治疗。她温柔善良，是枫丹人民健康的守护者。', '["水之治疗","水之复苏","水之再生","水元素亲和","医疗的守护","生命的祝福"]', '["水元素亲和","医疗的智慧","生命的守护"]', '赵爽', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (71, '阿蕾奇诺', '火元素', '长柄武器', 5, '枫丹', '枫丹的执行官，以火元素之力执行法律。', 'images/characters/aleichuo.png', '烈焰之刃', '烈焰燃烧', '烈焰审判', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["正义的教导","正义的指引","正义的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '阿蕾奇诺是枫丹的执行官，以火元素之力执行法律。她性格冷酷，是枫丹法律体系的重要执行者，拥有强大的火焰力量和坚定的意志。', '["烈焰之刃","烈焰燃烧","烈焰审判","火元素亲和","执行官的荣耀","法律的守护"]', '["火元素亲和","执行官的荣耀","法律的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (72, '那维莱特', '水元素', '法器', 5, '枫丹', '枫丹的最高审判官，原初的那维莱特，掌握水元素力量。', 'images/characters/naweilaite.png', '如水流转寻平衡', '泪之誓约', '潮之归返', '["浮涌之潮碎屑","浮涌之潮断片","浮涌之潮块","浮涌之潮","流光星髓","越洋珍珠","越洋碎块","异色谱晶"]', '["公正的教导","公正的指引","公正的哲学","永恒琥珀","越洋珍珠","越洋碎块","异色谱晶"]', 1020, 52, 34, '那维莱特是枫丹的最高审判官，原初的那维莱特，掌握着水元素的本源力量。他以公正严明的审判和深厚的智慧著称，是枫丹秩序的维护者。', '["原初的审判","如水流转寻平衡","泪之誓约","潮之归返","水元素亲和","审判的智慧"]', '["水元素亲和","审判的智慧","秩序的守护"]', '彭博', '神谷浩史');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (73, '莱欧斯利', '冰元素', '法器', 5, '枫丹', '梅洛彼得堡的管理者，以冰元素之力维护秩序。', 'images/characters/laiousili.png', '重拳制裁', '寒狱冰牢', '终审判决', '["哀叙冰玉碎屑","哀叙冰玉断片","哀叙冰玉块","哀叙冰玉","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["正义的教导","正义的指引","正义的哲学","极寒之核","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '莱欧斯利是梅洛彼得堡的管理者，以冰元素之力维护秩序。他以冷静理智的性格和强大的冰元素力量著称，是枫丹秩序的重要维护者。', '["冰之审判","重拳制裁","寒狱冰牢","终审判决","冰元素亲和","秩序的守护"]', '["冰元素亲和","秩序的守护","审判的智慧"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (74, '闲云', '风元素', '法器', 5, '璃月', '璃月港的隐士，擅长使用风元素。', 'images/characters/xianyun.png', '风之隐匿', '风之飘逸', '风之自由', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["繁荣的教导","繁荣的指引","繁荣的哲学","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '闲云是璃月港的神秘隐士，以风元素之力进行战斗。她性格淡泊名利，喜欢在山林间隐居修行，是璃月的智慧象征。', '["风之隐士","风之隐匿","风之飘逸","风之自由","风元素亲和","山林的守护"]', '["风元素亲和","山林的智慧","风之祝福"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (75, '嘉明', '火元素', '双手剑', 4, '璃月', '枫丹的工程师，擅长使用火元素。', 'images/characters/jiaming.png', '火之工程', '火之设计', '火之制造', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["正义的教导","正义的指引","正义的哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 920, 44, 28, '嘉明是枫丹的工程师，以火元素之力进行创作。他擅长设计各种机械装置，是枫丹工程领域的杰出人才。', '["火之工程","火之设计","火之制造","火元素亲和","工程师的智慧","创造的奥秘"]', '["火元素亲和","工程师的智慧","创造的灵感"]', '谢莹', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (76, '珊瑚宫心海', '水元素', '法器', 5, '稻妻', '稻妻海祇岛的“现人神巫女”，擅长谋略。', 'images/characters/xinhai.png', '水有常形', '海人化羽', '海月之誓', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","水之滴","净水之心","纯水之愿","浓缩树脂"]', '["雷电的教导","雷电的指引","雷电的哲学","芙宁娜的战利品","净水之心","纯水之愿","浓缩树脂"]', 1050, 50, 35, '珊瑚宫心海是稻妻海祇岛的“现人神巫女”，以水元素之力守护海祇岛的和平。她擅长谋略，是海祇岛的智慧象征。', '["海祇之心","水有常形","海人化羽","海月之誓","水元素亲和","谋略的智慧"]', '["水元素亲和","谋略的智慧","海祇的守护"]', '龟娘', '三森铃子');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (77, '玛薇卡', '火元素', '双手剑', 5, '纳塔', '新晋神明，输出能力和对战斗节奏的掌控力非常强劲，是当前版本最强的站场主C之一。', 'images/characters/mavica.png', '普攻', '火焰之怒', '烈焰之裁', '["燃愿玛瑙碎屑","燃愿玛瑙断片","燃愿玛瑙块","燃愿玛瑙","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', '["火之教导","火之指引","火之哲学","炎之花","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '玛薇卡是纳塔的新晋神明，以火元素之力进行战斗。她拥有强大的输出能力和对战斗节奏的掌控力，是当前版本最强的站场主C之一。', '["火焰之怒","烈焰之裁","火元素亲和","神明的祝福","战斗的节奏","火焰的掌控"]', '["火元素亲和","战斗的节奏","火焰的掌控"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (78, '希诺宁', '岩元素', '单手剑', 5, '纳塔', '纳塔有名的铸造师，由于有着高超的技艺对她崇拜有加，纷纷从各地慕名而来。', 'images/characters/xinuoning.png', '焮火铸魂', '焮火技艺', '焮火守护', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["豹猫座","豹猫座","豹猫座","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '希诺宁是纳塔有名的铸造师，以岩元素之力打造出无数精良武器。她的技艺高超，吸引了来自各地的崇拜者，是纳塔锻造业的传奇人物。', '["焮火铸魂","焮火技艺","焮火守护","岩元素亲和","铸造大师","炉火纯青"]', '["岩元素亲和","锻造精通","炉火的祝福"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (79, '基尼奇', '草元素', '双手剑', 5, '纳塔', '悬木人是部落中有名的猎龙者，在人与龙和洽共生的纳塔，猎龙人从诞生之初就无法获得所有人的理解。', 'images/characters/jiniqi.png', '回火之狩', '幻瑞兽座', '幻瑞兽座', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["幻瑞兽座","幻瑞兽座","幻瑞兽座","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 1020, 52, 34, '基尼奇是纳塔悬木人部落的猎龙者，以草元素之力与巨龙战斗。在人与龙共生的纳塔，他的存在充满了争议，但他始终坚持自己的道路。', '["回火之狩","幻瑞兽座","草元素亲和","猎龙者的荣耀","自然的守护","龙血的传承"]', '["草元素亲和","猎龙的直觉","自然的庇护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (80, '玛拉妮', '水元素', '法器', 5, '纳塔', '作为流泉之众新生代的一员，玛拉妮的名气早就传遍了纳塔，在她规划的路线上，可以欣赏到火山爆发的绚丽景色。', 'images/characters/malani.png', '哗啦啦逐浪客', '浪海豹座', '浪海豹座', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["浪海豹座","浪海豹座","浪海豹座","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '玛拉妮是流泉之众新生代的一员，以水元素之力进行战斗。她以火山爆发的绚丽景色为背景，展现出了独特的战斗风格和魅力。', '["流泉之众","哗啦啦逐浪客","浪海豹座","水元素亲和","火山的祝福","浪花的守护"]', '["水元素亲和","浪花的祝福","火山的守护"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (81, '欧洛伦', '雷元素', '弓箭', 4, '纳塔', '欧洛伦是纳塔烟谜主部落的成员，是纳塔的烟蝠。', 'images/characters/ouluolun.png', '深黯的谜烟', '夜蝠座', '夜蝠座', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["夜蝠座","夜蝠座","夜蝠座","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '欧洛伦是纳塔烟谜主部落的成员，以雷元素之力进行战斗。他拥有神秘的烟蝠能力，是纳塔的传奇人物。', '["烟谜主","深黯的谜烟","夜蝠座","雷元素亲和","烟雾的守护","谜烟的奥秘"]', '["雷元素亲和","烟雾的守护","谜烟的奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (82, '恰斯卡', '风元素', '弓箭', 5, '纳塔', '恰斯卡是花羽会部落的成员，各部落间远近闻名的调停人。', 'images/characters/qiasika.png', '巡宇翦定', '神鹫座', '神鹫座', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["神鹫座","神鹫座","神鹫座","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '恰斯卡是花羽会部落的成员，以风元素之力进行战斗。她以调停人身份闻名，是纳塔各部落之间的和平使者。', '["花羽会","巡宇翦定","神鹫座","风元素亲和","神鹫的守护","调停者的智慧"]', '["风元素亲和","神鹫的守护","调停者的智慧"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (83, '伊安珊', '雷元素', '长柄武器', 4, '纳塔', '伊安珊是沃陆之邦的战士，运动教练是她的本职工作。', 'images/characters/ianshan.png', '熔石百炼', '牨龙座', '牨龙座', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["牨龙座","牨龙座","牨龙座","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '伊安珊是沃陆之邦的战士，以雷元素之力进行战斗。她以运动教练的身份为职业，拥有强大的战斗力。', '["沃陆之邦","熔石百炼","牨龙座","雷元素亲和","战士的荣耀","力量的传承"]', '["雷元素亲和","战士的荣耀","力量的传承"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (84, '卡齐娜', '岩元素', '长柄武器', 4, '纳塔', '斑金矿朴，纳茨卡延的年轻勇士。', 'images/characters/kazina.png', '斑金矿朴', '鼠兔座', '鼠兔座', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["鼠兔座","鼠兔座","鼠兔座","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '卡齐娜是纳塔纳茨卡延的年轻勇士，以岩元素之力进行战斗。她拥有强大的力量和坚韧的意志，是纳塔地区的杰出战士。', '["纳茨卡延","斑金矿朴","鼠兔座","岩元素亲和","矿石的祝福","勇士的荣耀"]', '["岩元素亲和","矿石的祝福","勇士的荣耀"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (85, '茜特菈莉', '冰元素', '法器', 5, '纳塔', '纳塔米克特兰的观星者，擅长使用水元素。', 'images/characters/chestina.png', '水元素攻击', '水元素技能', '水元素防御', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["米克特兰的教导","米克特兰的指引","米克特兰的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '茜特菈莉是纳塔米克特兰的观星者，以水元素之力进行战斗。她精通天文观测和水元素的运用，是纳塔地区的智慧象征。', '["米克特兰","水元素攻击","水元素技能","水元素防御","水之智慧","星辰的守护"]', '["水元素亲和","星辰的祝福","水之智慧"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (86, '瓦雷莎', '雷元素', '法器', 5, '纳塔', '纳塔沃陆之邦的中坚战士，擅长使用岩元素。', 'images/characters/valesha.png', '岩元素攻击', '岩元素技能', '岩元素防御', '["坚牢黄玉碎屑","坚牢黄玉断片","坚牢黄玉块","坚牢黄玉","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["沃陆之邦的教导","沃陆之邦的指引","沃陆之邦的哲学","岩之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '瓦雷莎是纳塔沃陆之邦的中坚战士，以雷元素之力进行战斗。她以岩元素为辅助，展现出强大的战斗能力。', '["沃陆之邦","岩元素攻击","岩元素技能","岩元素防御","雷之守护","战士的荣耀"]', '["雷元素亲和","岩元素辅助","战士的荣耀"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (87, '伊法', '风元素', '法器', 4, '纳塔', '纳塔特拉洛坎的兽医，擅长使用风元素。', 'images/characters/iffa.png', '风元素攻击', '风元素技能', '风元素防御', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["特拉洛坎的教导","特拉洛坎的指引","特拉洛坎的哲学","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '伊法是纳塔特拉洛坎的兽医，以风元素之力进行战斗。她精通动物医学和风元素的运用，是纳塔地区的医疗专家。', '["特拉洛坎","风元素攻击","风元素技能","风元素防御","风之守护","兽医的智慧"]', '["风元素亲和","风之守护","兽医的智慧"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (88, '爱诺', '水元素', '法器', 4, '挪德卡莱', '叮铃哐当蛋卷工坊的主人，擅长制造各种机械，重新拼装了伊涅芙。', 'images/characters/ainuo.png', '机械制造', '家政机器人', '元素操控', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["挪德卡莱的教导","挪德卡莱的指引","挪德卡莱的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 960, 46, 30, '爱诺是挪德卡莱叮铃哐当蛋卷工坊的主人，擅长制造各种机械，重新拼装了伊涅芙。她以水元素之力进行战斗，展现出独特的机械与元素结合的战斗风格。', '["机械之心","家政机器人","元素操控","水元素亲和","机械的祝福","创造的奥秘"]', '["水元素亲和","机械的祝福","创造的奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (89, '伊涅芙', '雷元素', '单手剑', 5, '挪德卡莱', '首位空月之歌系列角色，带来全新反应——月感电。', 'images/characters/yinefu.png', '月感电', '空月之歌', '元素反应', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["空月的教导","空月的指引","空月的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '伊涅芙是首位空月之歌系列角色，带来全新反应——月感电。她以雷元素之力进行战斗，展现出独特的战斗风格和魅力。', '["空月之歌","月感电","元素反应","雷元素亲和","月之祝福","空月的奥秘"]', '["雷元素亲和","月之祝福","空月的奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (90, '雅珂达', '风元素', '弓箭', 4, '挪德卡莱', '叮呤哐啷蛋卷工坊的新角色，风格新颖独特。', 'images/characters/yakeda.png', '风元素攻击', '风元素技能', '风元素防御', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["雅珂达的教导","雅珂达的指引","雅珂达的哲学","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '雅珂达是挪德卡莱叮呤哐啷蛋卷工坊的新角色，以风元素之力进行战斗。她以新颖独特的风格和强大的风元素力量著称。', '["风之舞者","风元素攻击","风元素技能","风元素防御","风之祝福","风之奥秘"]', '["风元素亲和","风之祝福","风之奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (91, '杜林', '火元素', '单手剑', 5, '蒙德', '化形后的形象非常优秀帅气，符合剧情塑造。', 'images/characters/dulin.png', '岩元素攻击', '岩元素技能', '岩元素防御', '["自在松石碎屑","自在松石断片","自在松石块","自在松石","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["杜林的教导","杜林的指引","杜林的哲学","东风之翎","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '杜林是挪德卡莱的化形者，以火元素之力进行战斗。他以优秀帅气的形象和强大的战斗力著称，是挪德卡莱的传奇人物。', '["化形者","岩元素攻击","岩元素技能","岩元素防御","火之祝福","化形的奥秘"]', '["火元素亲和","化形的祝福","火之奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (92, '菲林斯', '雷元素', '长柄武器', 5, '挪德卡莱', '执灯人的首领，雷系神之眼，奈芙尔伏尼奇商会阵营。', 'images/characters/feilinsi.png', '雷元素攻击', '雷元素技能', '雷元素防御', '["雷霆数珠碎屑","雷霆数珠断片","雷霆数珠块","雷霆数珠","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', '["执灯人的教导","执灯人的指引","执灯人的哲学","雷之心","史莱姆凝液","史莱姆清","史莱姆原浆"]', 1020, 52, 34, '菲林斯是挪德卡莱执灯人的首领，以雷元素之力进行战斗。他是奈芙尔伏尼奇商会阵营的重要人物，拥有强大的雷元素力量和领导才能。', '["执灯人","雷元素攻击","雷元素技能","雷元素防御","雷之守护","执灯人的智慧"]', '["雷元素亲和","雷之守护","执灯人的智慧"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (93, '奈芙尔', '水元素', '法器', 5, '挪德卡莱', '伏尼奇商会阵营，知道不少古老的故事，背景不简单。', 'images/characters/naiful.png', '水元素攻击', '水元素技能', '水元素防御', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', '["伏尼奇的教导","伏尼奇的指引","伏尼奇的哲学","净水之心","骗骗花蜜","微光花蜜","原素花蜜"]', 1020, 52, 34, '奈芙尔是挪德卡莱伏尼奇商会阵营的重要人物，知道不少古老的故事，背景不简单。她以水元素之力进行战斗，展现出神秘而强大的力量。', '["伏尼奇商会","水元素攻击","水元素技能","水元素防御","水之智慧","古老的秘密"]', '["水元素亲和","古老的智慧","水之奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (94, '菈乌玛', '草元素', '法器', 5, '挪德卡莱', '霜月之子部落的祭司角色，以草元素角色身份登场。', 'images/characters/lawuma.png', '草元素攻击', '草元素技能', '草元素防御', '["生长碧翡碎屑","生长碧翡断片","生长碧翡块","生长碧翡","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', '["霜月之子的教导","霜月之子的指引","霜月之子的哲学","枯荣之实","蕈兽孢子","荧光孢粉","孢囊晶尘"]', 1020, 52, 34, '菈乌玛是挪德卡莱霜月之子部落的祭司角色，以草元素之力进行战斗。她作为部落的祭司，掌握着古老的草元素知识和神秘的力量。', '["霜月之子","草元素攻击","草元素技能","草元素防御","草之智慧","古老的祭典"]', '["草元素亲和","古老的智慧","草之奥秘"]', '季冠霖', '石见舞菜香');
INSERT INTO `characters` (`id`, `name`, `element`, `weapon`, `rarity`, `region`, `description`, `image`, `normal_attack`, `elemental_skill`, `elemental_burst`, `ascension_materials`, `talent_materials`, `base_hp`, `base_atk`, `base_def`, `character_story`, `constellations`, `passive_talents`, `voice_actor_cn`, `voice_actor_jp`) VALUES (95, '哥伦比娅', '水元素', '法器', 5, '挪德卡莱', '“月之少女”，剧情设定为新月神，可输出可辅助，是月反应体系核心。', 'images/characters/gelunbiya.png', '月露泼降', '万古潮汐', '她的乡愁', '["涤净青金碎屑","涤净青金断片","涤净青金块","涤净青金","漫天的辉角","史莱姆凝胶","史莱姆清","史莱姆原浆"]', '["月光的教导","月光的指引","月光的哲学","贤者的假面","史莱姆凝胶","史莱姆清","史莱姆原浆"]', 1050, 50, 35, '哥伦比娅是“月之少女”，剧情设定为新月神，可输出可辅助，是月反应体系的核心角色。她拥有强大的水元素力量和独特的月感电反应能力。', '["新月神","月露泼降","万古潮汐","她的乡愁","月光的祝福","潮汐的守护"]', '["月光的祝福","潮汐的守护","月感电反应"]', '季冠霖', '石见舞菜香');

-- Table: favorites
CREATE TABLE IF NOT EXISTS `favorites` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `character_id` int NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_character` (`user_id`,`character_id`),
  KEY `character_id` (`character_id`),
  CONSTRAINT `favorites_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `favorites_ibfk_2` FOREIGN KEY (`character_id`) REFERENCES `characters` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (1, 1, 2);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (2, 1, 4);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (4, 1, 9);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (3, 1, 11);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (5, 1, 12);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (7, 1, 14);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (6, 1, 15);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (8, 1, 33);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (9, 1, 41);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (10, 1, 52);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (11, 1, 62);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (13, 1, 65);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (12, 1, 66);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (14, 1, 76);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (15, 1, 80);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (17, 1, 85);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (16, 1, 86);
INSERT INTO `favorites` (`id`, `user_id`, `character_id`) VALUES (18, 1, 95);

